import { z } from 'zod';
import { authenticatedProcedure, router } from '../trpc';
import {
  AuditActionType,
  AuditSeverity,
  createAuditService,
} from '@glapi/api-service';

const evidenceFiltersSchema = z
  .object({
    resourceTypes: z.array(z.string()).min(1).optional(),
    actionTypes: z.array(z.nativeEnum(AuditActionType)).min(1).optional(),
    actorIds: z.array(z.string()).min(1).optional(),
    severity: z.array(z.nativeEnum(AuditSeverity)).min(1).optional(),
  })
  .optional();

const paginationSchema = z
  .object({
    page: z.number().min(1).optional(),
    limit: z.number().min(1).max(100).optional(),
  })
  .optional();

export const auditRouter = router({
  createEvidencePackage: authenticatedProcedure
    .input(
      z.object({
        packageName: z.string().min(3),
        description: z.string().optional(),
        startDate: z.coerce.date(),
        endDate: z.coerce.date(),
        filters: evidenceFiltersSchema,
        expiresInDays: z.number().int().min(1).max(365).optional(),
        changeRequestId: z.string().uuid().optional(),
        autoGenerated: z.boolean().optional(),
      })
    )
    .mutation(async ({ ctx, input }) => {
      const service = createAuditService(ctx.serviceContext);
      return service.createEvidencePackage({
        packageName: input.packageName,
        description: input.description,
        startDate: input.startDate,
        endDate: input.endDate,
        filters: input.filters || undefined,
        expiresInDays: input.expiresInDays,
        changeRequestId: input.changeRequestId,
        autoGenerated: input.autoGenerated,
      });
    }),

  listEvidencePackages: authenticatedProcedure
    .input(paginationSchema)
    .query(async ({ ctx, input }) => {
      const service = createAuditService(ctx.serviceContext);
      return service.listEvidencePackages({
        page: input?.page,
        limit: input?.limit,
      });
    }),

  getEvidencePackage: authenticatedProcedure
    .input(z.object({ id: z.string().uuid() }))
    .query(async ({ ctx, input }) => {
      const service = createAuditService(ctx.serviceContext);
      const pkg = await service.getEvidencePackage(input.id);
      if (!pkg) {
        throw new Error('Evidence package not found');
      }
      return pkg;
    }),

  generateEvidenceBundle: authenticatedProcedure
    .input(
      z.object({
        packageId: z.string().uuid(),
        includeRawLogs: z.boolean().optional(),
        includeApprovals: z.boolean().optional(),
        includeCodeReferences: z.boolean().optional(),
        changeRequestId: z.string().uuid().optional(),
      })
    )
    .mutation(async ({ ctx, input }) => {
      const service = createAuditService(ctx.serviceContext);
      const result = await service.generateEvidenceBundle(input.packageId, {
        includeRawLogs: input.includeRawLogs,
        includeApprovals: input.includeApprovals,
        includeCodeReferences: input.includeCodeReferences,
        persistToDisk: false,
        changeRequestId: input.changeRequestId,
      });

      return {
        manifest: result.manifest,
        contentHash: result.contentHash,
        size: result.size,
        bundleBase64: result.bundle.toString('base64'),
      };
    }),
});
