import { pgTable, text, boolean, timestamp, uniqueIndex, decimal, date, uuid, integer, AnyPgColumn } from 'drizzle-orm/pg-core';
import { relations } from 'drizzle-orm';
import { accountingPeriods } from './accounting-periods';

export const glTransactions = pgTable('gl_transactions', {
  id: uuid('id').defaultRandom().primaryKey(),
  transactionNumber: text('transaction_number').notNull().unique(),
  subsidiaryId: uuid('subsidiary_id').notNull(),
  transactionDate: date('transaction_date').notNull(),
  postingDate: date('posting_date').notNull(),
  periodId: uuid('period_id').notNull(),
  transactionType: text('transaction_type').notNull(), // 'JOURNAL', 'POSTING', 'REVERSAL', 'CLOSING'
  sourceSystem: text('source_system'), // 'MANUAL', 'AUTO', 'IMPORT'
  sourceTransactionId: uuid('source_transaction_id').references(() => businessTransactions.id),
  sourceTransactionType: text('source_transaction_type'),
  description: text('description'),
  referenceNumber: text('reference_number'),
  baseCurrencyCode: text('base_currency_code').notNull(),
  totalDebitAmount: decimal('total_debit_amount', { precision: 18, scale: 4 }).notNull(),
  totalCreditAmount: decimal('total_credit_amount', { precision: 18, scale: 4 }).notNull(),
  status: text('status').notNull(), // 'DRAFT', 'PENDING', 'POSTED', 'REVERSED'
  recurringTemplateId: uuid('recurring_template_id'),
  reversedByTransactionId: uuid('reversed_by_transaction_id').references((): AnyPgColumn => glTransactions.id),
  reversalReason: text('reversal_reason'),
  autoGenerated: boolean('auto_generated').default(false).notNull(),
  
  // Audit fields
  createdBy: uuid('created_by').references(() => users.id),
  createdDate: timestamp('created_date', { withTimezone: true }).defaultNow().notNull(),
  modifiedBy: uuid('modified_by').references(() => users.id),
  modifiedDate: timestamp('modified_date', { withTimezone: true }).defaultNow().notNull(),
  postedBy: uuid('posted_by').references(() => users.id),
  postedDate: timestamp('posted_date', { withTimezone: true }),
  versionNumber: integer('version_number').default(1).notNull(),
}, (table) => ({
  transactionNumberIdx: uniqueIndex('idx_gl_trans_number').on(table.transactionNumber),
  dateAndSubIdx: uniqueIndex('idx_gl_trans_date_sub').on(table.transactionDate, table.subsidiaryId),
  periodIdx: uniqueIndex('idx_gl_trans_period').on(table.periodId, table.status),
  sourceIdx: uniqueIndex('idx_gl_trans_source').on(table.sourceTransactionId),
}));

export const glTransactionsRelations = relations(glTransactions, ({ one, many }) => ({
  subsidiary: one(subsidiaries, {
    fields: [glTransactions.subsidiaryId],
    references: [subsidiaries.id],
  }),
  period: one(accountingPeriods, {
    fields: [glTransactions.periodId],
    references: [accountingPeriods.id],
  }),
  sourceTransaction: one(businessTransactions, {
    fields: [glTransactions.sourceTransactionId],
    references: [businessTransactions.id],
  }),
  reversedBy: one(glTransactions, {
    fields: [glTransactions.reversedByTransactionId],
    references: [glTransactions.id],
  }),
  createdByUser: one(users, {
    fields: [glTransactions.createdBy],
    references: [users.id],
    relationName: 'createdBy',
  }),
  modifiedByUser: one(users, {
    fields: [glTransactions.modifiedBy],
    references: [users.id],
    relationName: 'modifiedBy',
  }),
  postedByUser: one(users, {
    fields: [glTransactions.postedBy],
    references: [users.id],
    relationName: 'postedBy',
  }),
  lines: many(glTransactionLines),
}));

export const glTransactionLines = pgTable('gl_transaction_lines', {
  id: uuid('id').defaultRandom().primaryKey(),
  transactionId: uuid('transaction_id').notNull().references(() => glTransactions.id, { onDelete: 'cascade' }),
  lineNumber: integer('line_number').notNull(),
  accountId: uuid('account_id').notNull(),
  classId: uuid('class_id'),
  departmentId: uuid('department_id'),
  locationId: uuid('location_id'),
  subsidiaryId: uuid('subsidiary_id').notNull(),
  debitAmount: decimal('debit_amount', { precision: 18, scale: 4 }).default('0').notNull(),
  creditAmount: decimal('credit_amount', { precision: 18, scale: 4 }).default('0').notNull(),
  currencyCode: text('currency_code').notNull(),
  exchangeRate: decimal('exchange_rate', { precision: 12, scale: 6 }).default('1').notNull(),
  baseDebitAmount: decimal('base_debit_amount', { precision: 18, scale: 4 }).default('0').notNull(),
  baseCreditAmount: decimal('base_credit_amount', { precision: 18, scale: 4 }).default('0').notNull(),
  description: text('description'),
  reference1: text('reference_1'),
  reference2: text('reference_2'),
  projectId: uuid('project_id'),
  createdDate: timestamp('created_date', { withTimezone: true }).defaultNow().notNull(),
}, (table) => ({
  transactionLineIdx: uniqueIndex('idx_gl_line_trans').on(table.transactionId, table.lineNumber),
  accountIdx: uniqueIndex('idx_gl_line_account').on(table.accountId, table.transactionId),
}));

export const glTransactionLinesRelations = relations(glTransactionLines, ({ one }) => ({
  transaction: one(glTransactions, {
    fields: [glTransactionLines.transactionId],
    references: [glTransactions.id],
  }),
  account: one(accounts, {
    fields: [glTransactionLines.accountId],
    references: [accounts.id],
  }),
  class: one(classes, {
    fields: [glTransactionLines.classId],
    references: [classes.id],
  }),
  department: one(departments, {
    fields: [glTransactionLines.departmentId],
    references: [departments.id],
  }),
  location: one(locations, {
    fields: [glTransactionLines.locationId],
    references: [locations.id],
  }),
  subsidiary: one(subsidiaries, {
    fields: [glTransactionLines.subsidiaryId],
    references: [subsidiaries.id],
  }),
}));

export const glPostingRules = pgTable('gl_posting_rules', {
  id: uuid('id').defaultRandom().primaryKey(),
  transactionTypeId: uuid('transaction_type_id').notNull().references(() => transactionTypes.id),
  subsidiaryId: uuid('subsidiary_id'), // Optional: null means global
  ruleName: text('rule_name').notNull(),
  sequenceNumber: integer('sequence_number').default(10).notNull(),
  lineType: text('line_type'), // Maps to business transaction line types
  conditionSql: text('condition_sql'), // SQL expression for advanced conditions
  debitAccountId: uuid('debit_account_id'),
  creditAccountId: uuid('credit_account_id'),
  amountFormula: text('amount_formula'), // Expression to calculate amount
  descriptionTemplate: text('description_template'), // Template for GL line description
  isActive: boolean('is_active').default(true).notNull(),
  effectiveDate: date('effective_date').notNull(),
  expirationDate: date('expiration_date'),
  createdBy: uuid('created_by').references(() => users.id),
  createdDate: timestamp('created_date', { withTimezone: true }).defaultNow().notNull(),
  modifiedDate: timestamp('modified_date', { withTimezone: true }).defaultNow().notNull(),
}, (table) => ({
  typeAndSubIdx: uniqueIndex('idx_posting_rules_type_sub').on(table.transactionTypeId, table.subsidiaryId),
  activeIdx: uniqueIndex('idx_posting_rules_active').on(table.isActive, table.effectiveDate),
}));

export const glPostingRulesRelations = relations(glPostingRules, ({ one }) => ({
  transactionType: one(transactionTypes, {
    fields: [glPostingRules.transactionTypeId],
    references: [transactionTypes.id],
  }),
  subsidiary: one(subsidiaries, {
    fields: [glPostingRules.subsidiaryId],
    references: [subsidiaries.id],
  }),
  debitAccount: one(accounts, {
    fields: [glPostingRules.debitAccountId],
    references: [accounts.id],
    relationName: 'debitAccount',
  }),
  creditAccount: one(accounts, {
    fields: [glPostingRules.creditAccountId],
    references: [accounts.id],
    relationName: 'creditAccount',
  }),
}));

export const glAccountBalances = pgTable('gl_account_balances', {
  id: uuid('id').defaultRandom().primaryKey(),
  accountId: uuid('account_id').notNull(),
  subsidiaryId: uuid('subsidiary_id').notNull(),
  periodId: uuid('period_id').notNull(),
  classId: uuid('class_id'),
  departmentId: uuid('department_id'),
  locationId: uuid('location_id'),
  currencyCode: text('currency_code').notNull(),
  beginningBalanceDebit: decimal('beginning_balance_debit', { precision: 18, scale: 4 }).default('0').notNull(),
  beginningBalanceCredit: decimal('beginning_balance_credit', { precision: 18, scale: 4 }).default('0').notNull(),
  periodDebitAmount: decimal('period_debit_amount', { precision: 18, scale: 4 }).default('0').notNull(),
  periodCreditAmount: decimal('period_credit_amount', { precision: 18, scale: 4 }).default('0').notNull(),
  endingBalanceDebit: decimal('ending_balance_debit', { precision: 18, scale: 4 }).default('0').notNull(),
  endingBalanceCredit: decimal('ending_balance_credit', { precision: 18, scale: 4 }).default('0').notNull(),
  ytdDebitAmount: decimal('ytd_debit_amount', { precision: 18, scale: 4 }).default('0').notNull(),
  ytdCreditAmount: decimal('ytd_credit_amount', { precision: 18, scale: 4 }).default('0').notNull(),
  baseBeginningBalanceDebit: decimal('base_beginning_balance_debit', { precision: 18, scale: 4 }).default('0').notNull(),
  baseBeginningBalanceCredit: decimal('base_beginning_balance_credit', { precision: 18, scale: 4 }).default('0').notNull(),
  basePeriodDebitAmount: decimal('base_period_debit_amount', { precision: 18, scale: 4 }).default('0').notNull(),
  basePeriodCreditAmount: decimal('base_period_credit_amount', { precision: 18, scale: 4 }).default('0').notNull(),
  baseEndingBalanceDebit: decimal('base_ending_balance_debit', { precision: 18, scale: 4 }).default('0').notNull(),
  baseEndingBalanceCredit: decimal('base_ending_balance_credit', { precision: 18, scale: 4 }).default('0').notNull(),
  baseYtdDebitAmount: decimal('base_ytd_debit_amount', { precision: 18, scale: 4 }).default('0').notNull(),
  baseYtdCreditAmount: decimal('base_ytd_credit_amount', { precision: 18, scale: 4 }).default('0').notNull(),
  lastUpdated: timestamp('last_updated', { withTimezone: true }).defaultNow().notNull(),
}, (table) => ({
  accountPeriodIdx: uniqueIndex('idx_balance_account_period').on(table.accountId, table.periodId),
  subPeriodIdx: uniqueIndex('idx_balance_sub_period').on(table.subsidiaryId, table.periodId),
  dimensionsIdx: uniqueIndex('idx_balance_dimensions').on(
    table.accountId,
    table.subsidiaryId,
    table.periodId,
    table.classId,
    table.departmentId,
    table.locationId,
    table.currencyCode
  ),
}));

export const glAccountBalancesRelations = relations(glAccountBalances, ({ one }) => ({
  account: one(accounts, {
    fields: [glAccountBalances.accountId],
    references: [accounts.id],
  }),
  subsidiary: one(subsidiaries, {
    fields: [glAccountBalances.subsidiaryId],
    references: [subsidiaries.id],
  }),
  period: one(accountingPeriods, {
    fields: [glAccountBalances.periodId],
    references: [accountingPeriods.id],
  }),
  class: one(classes, {
    fields: [glAccountBalances.classId],
    references: [classes.id],
  }),
  department: one(departments, {
    fields: [glAccountBalances.departmentId],
    references: [departments.id],
  }),
  location: one(locations, {
    fields: [glAccountBalances.locationId],
    references: [locations.id],
  }),
}));

export const glAuditTrail = pgTable('gl_audit_trail', {
  id: uuid('id').defaultRandom().primaryKey(),
  tableName: text('table_name').notNull(),
  recordId: uuid('record_id').notNull(),
  actionType: text('action_type').notNull(), // 'INSERT', 'UPDATE', 'DELETE'
  fieldName: text('field_name'),
  oldValue: text('old_value'),
  newValue: text('new_value'),
  userId: uuid('user_id').notNull().references(() => users.id),
  sessionId: text('session_id'),
  ipAddress: text('ip_address'),
  timestamp: timestamp('timestamp', { withTimezone: true }).defaultNow().notNull(),
}, (table) => ({
  tableRecordIdx: uniqueIndex('idx_audit_table_record').on(table.tableName, table.recordId),
  userIdx: uniqueIndex('idx_audit_user').on(table.userId, table.timestamp),
}));

export const glAuditTrailRelations = relations(glAuditTrail, ({ one }) => ({
  user: one(users, {
    fields: [glAuditTrail.userId],
    references: [users.id],
  }),
}));

// Import references
import { subsidiaries } from './subsidiaries';
import { users } from './users';
import { accounts } from './accounts';
import { classes } from './classes';
import { departments } from './departments';
import { locations } from './locations';
import { businessTransactions } from './transaction-types';
import { transactionTypes } from './transaction-types';