export declare const transactionTypes: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "transaction_types";
    schema: undefined;
    columns: {
        id: import("drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "transaction_types";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        typeCode: import("drizzle-orm/pg-core").PgColumn<{
            name: "type_code";
            tableName: "transaction_types";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        typeName: import("drizzle-orm/pg-core").PgColumn<{
            name: "type_name";
            tableName: "transaction_types";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        typeCategory: import("drizzle-orm/pg-core").PgColumn<{
            name: "type_category";
            tableName: "transaction_types";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        generatesGl: import("drizzle-orm/pg-core").PgColumn<{
            name: "generates_gl";
            tableName: "transaction_types";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        requiresApproval: import("drizzle-orm/pg-core").PgColumn<{
            name: "requires_approval";
            tableName: "transaction_types";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        canBeReversed: import("drizzle-orm/pg-core").PgColumn<{
            name: "can_be_reversed";
            tableName: "transaction_types";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        numberingSequence: import("drizzle-orm/pg-core").PgColumn<{
            name: "numbering_sequence";
            tableName: "transaction_types";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        defaultGlAccountId: import("drizzle-orm/pg-core").PgColumn<{
            name: "default_gl_account_id";
            tableName: "transaction_types";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        workflowTemplate: import("drizzle-orm/pg-core").PgColumn<{
            name: "workflow_template";
            tableName: "transaction_types";
            dataType: "json";
            columnType: "PgJsonb";
            data: unknown;
            driverParam: unknown;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        isActive: import("drizzle-orm/pg-core").PgColumn<{
            name: "is_active";
            tableName: "transaction_types";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        sortOrder: import("drizzle-orm/pg-core").PgColumn<{
            name: "sort_order";
            tableName: "transaction_types";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        createdAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "created_at";
            tableName: "transaction_types";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        updatedAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "updated_at";
            tableName: "transaction_types";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const transactionTypesRelations: import("drizzle-orm").Relations<"transaction_types", {
    businessTransactions: import("drizzle-orm").Many<any>;
}>;
export declare const businessTransactions: any;
export declare const businessTransactionsRelations: import("drizzle-orm").Relations<string, {
    transactionType: import("drizzle-orm").One<"transaction_types", false>;
    subsidiary: import("drizzle-orm").One<"subsidiaries", false>;
    entity: import("drizzle-orm").One<"entities", false>;
    paymentTerms: import("drizzle-orm").One<"payment_terms", false>;
    department: import("drizzle-orm").One<"departments", false>;
    class: import("drizzle-orm").One<"classes", false>;
    location: import("drizzle-orm").One<"locations", false>;
    billingAddress: import("drizzle-orm").One<"addresses", false>;
    shippingAddress: import("drizzle-orm").One<"addresses", false>;
    parentTransaction: import("drizzle-orm").One<any, false>;
    lines: import("drizzle-orm").Many<any>;
    childTransactions: import("drizzle-orm").Many<any>;
    parentRelationships: import("drizzle-orm").Many<"transaction_relationships">;
    childRelationships: import("drizzle-orm").Many<"transaction_relationships">;
}>;
export declare const businessTransactionLines: any;
export declare const businessTransactionLinesRelations: import("drizzle-orm").Relations<string, {
    businessTransaction: import("drizzle-orm").One<any, false>;
    item: import("drizzle-orm").One<"products", false>;
    taxCode: import("drizzle-orm").One<"tax_codes", false>;
    account: import("drizzle-orm").One<any, false>;
    department: import("drizzle-orm").One<"departments", false>;
    class: import("drizzle-orm").One<"classes", false>;
    location: import("drizzle-orm").One<"locations", false>;
    activityCode: import("drizzle-orm").One<"activity_codes", false>;
    employee: import("drizzle-orm").One<"entities", false>;
    parentLine: import("drizzle-orm").One<any, false>;
    childLines: import("drizzle-orm").Many<any>;
    parentRelationships: import("drizzle-orm").Many<"transaction_relationships">;
    childRelationships: import("drizzle-orm").Many<"transaction_relationships">;
}>;
export declare const transactionRelationships: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "transaction_relationships";
    schema: undefined;
    columns: {
        id: import("drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "transaction_relationships";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        parentTransactionId: import("drizzle-orm/pg-core").PgColumn<{
            name: "parent_transaction_id";
            tableName: "transaction_relationships";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        childTransactionId: import("drizzle-orm/pg-core").PgColumn<{
            name: "child_transaction_id";
            tableName: "transaction_relationships";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        relationshipType: import("drizzle-orm/pg-core").PgColumn<{
            name: "relationship_type";
            tableName: "transaction_relationships";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        appliedAmount: import("drizzle-orm/pg-core").PgColumn<{
            name: "applied_amount";
            tableName: "transaction_relationships";
            dataType: "string";
            columnType: "PgNumeric";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        parentLineId: import("drizzle-orm/pg-core").PgColumn<{
            name: "parent_line_id";
            tableName: "transaction_relationships";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        childLineId: import("drizzle-orm/pg-core").PgColumn<{
            name: "child_line_id";
            tableName: "transaction_relationships";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        createdDate: import("drizzle-orm/pg-core").PgColumn<{
            name: "created_date";
            tableName: "transaction_relationships";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        notes: import("drizzle-orm/pg-core").PgColumn<{
            name: "notes";
            tableName: "transaction_relationships";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const transactionRelationshipsRelations: import("drizzle-orm").Relations<"transaction_relationships", {
    parentTransaction: import("drizzle-orm").One<any, true>;
    childTransaction: import("drizzle-orm").One<any, true>;
    parentLine: import("drizzle-orm").One<any, false>;
    childLine: import("drizzle-orm").One<any, false>;
}>;
export declare const paymentTerms: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "payment_terms";
    schema: undefined;
    columns: {
        id: import("drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "payment_terms";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        subsidiaryId: import("drizzle-orm/pg-core").PgColumn<{
            name: "subsidiary_id";
            tableName: "payment_terms";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        termsCode: import("drizzle-orm/pg-core").PgColumn<{
            name: "terms_code";
            tableName: "payment_terms";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        termsName: import("drizzle-orm/pg-core").PgColumn<{
            name: "terms_name";
            tableName: "payment_terms";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        discountPercent: import("drizzle-orm/pg-core").PgColumn<{
            name: "discount_percent";
            tableName: "payment_terms";
            dataType: "string";
            columnType: "PgNumeric";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        discountDays: import("drizzle-orm/pg-core").PgColumn<{
            name: "discount_days";
            tableName: "payment_terms";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        netDays: import("drizzle-orm/pg-core").PgColumn<{
            name: "net_days";
            tableName: "payment_terms";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        isActive: import("drizzle-orm/pg-core").PgColumn<{
            name: "is_active";
            tableName: "payment_terms";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        createdAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "created_at";
            tableName: "payment_terms";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const paymentTermsRelations: import("drizzle-orm").Relations<"payment_terms", {
    businessTransactions: import("drizzle-orm").Many<any>;
}>;
//# sourceMappingURL=transaction-types.d.ts.map