import { BaseService } from './base-service';
import { 
  BusinessTransaction,
  BusinessTransactionLine,
  GlTransaction,
  GlTransactionLine,
  GlPostingRule,
  CreateGlTransactionInput,
  CreateGlTransactionLineInput,
  ServiceError
} from '../types';

export interface PostingResult {
  glTransaction: GlTransaction;
  glLines: GlTransactionLine[];
  balanceUpdates: AccountBalanceUpdate[];
}

export interface AccountBalanceUpdate {
  accountId: string;
  subsidiaryId: string;
  periodId: string;
  classId?: string;
  departmentId?: string;
  locationId?: string;
  currencyCode: string;
  debitAmount: number;
  creditAmount: number;
}

export interface PostingContext {
  businessTransaction: BusinessTransaction;
  businessTransactionLines: BusinessTransactionLine[];
  postingRules: GlPostingRule[];
  baseCurrencyCode: string;
  periodId: string;
}

export class GlPostingEngine extends BaseService {
  
  constructor(context = {}) {
    super(context);
  }

  /**
   * Generate GL entries for a business transaction
   */
  async generateGlEntries(context: PostingContext): Promise<PostingResult> {
    const organizationId = this.requireOrganizationContext();
    const userId = this.requireUserContext();
    
    // Validate posting context
    this.validatePostingContext(context);
    
    // Generate GL transaction header
    const glTransaction = await this.createGlTransactionHeader(context);
    
    // Generate GL lines based on posting rules
    const glLines = await this.generateGlLines(context, glTransaction.id!);
    
    // Validate GL transaction is balanced
    this.validateGlBalance(glLines);
    
    // Calculate balance updates
    const balanceUpdates = this.calculateBalanceUpdates(glLines, context);
    
    return {
      glTransaction,
      glLines,
      balanceUpdates
    };
  }

  /**
   * Validate posting context has all required data
   */
  private validatePostingContext(context: PostingContext): void {
    if (!context.businessTransaction) {
      throw new ServiceError(
        'Business transaction is required for posting',
        'MISSING_BUSINESS_TRANSACTION',
        400
      );
    }

    if (!context.businessTransactionLines?.length) {
      throw new ServiceError(
        'Business transaction must have at least one line',
        'MISSING_TRANSACTION_LINES',
        400
      );
    }

    if (!context.postingRules?.length) {
      throw new ServiceError(
        'No posting rules found for transaction type',
        'MISSING_POSTING_RULES',
        400
      );
    }

    if (!context.periodId) {
      throw new ServiceError(
        'Accounting period is required for posting',
        'MISSING_PERIOD',
        400
      );
    }
  }

  /**
   * Create GL transaction header
   */
  private async createGlTransactionHeader(context: PostingContext): Promise<GlTransaction> {
    const transactionNumber = await this.generateGlTransactionNumber(context.businessTransaction.subsidiaryId);
    
    const glTransaction: CreateGlTransactionInput = {
      transactionNumber,
      subsidiaryId: context.businessTransaction.subsidiaryId,
      transactionDate: context.businessTransaction.transactionDate,
      postingDate: new Date().toISOString().split('T')[0], // Today's date
      periodId: context.periodId,
      transactionType: 'POSTING',
      sourceSystem: 'AUTO',
      sourceTransactionId: context.businessTransaction.id!,
      sourceTransactionType: 'BUSINESS_TRANSACTION',
      description: `Auto-posted from ${context.businessTransaction.transactionNumber}`,
      referenceNumber: context.businessTransaction.externalReference,
      baseCurrencyCode: context.baseCurrencyCode,
      totalDebitAmount: '0', // Will be calculated from lines
      totalCreditAmount: '0', // Will be calculated from lines
      status: 'POSTED',
      autoGenerated: true,
      createdBy: this.requireUserContext(),
      postedBy: this.requireUserContext(),
      postedDate: new Date(),
    };

    // TODO: Replace with actual repository call
    return {
      ...glTransaction,
      id: `gl-${Date.now()}`, // Temporary ID
      createdDate: new Date(),
      modifiedDate: new Date(),
      versionNumber: 1,
    } as GlTransaction;
  }

  /**
   * Generate GL transaction number
   */
  private async generateGlTransactionNumber(subsidiaryId: string): Promise<string> {
    // TODO: Implement proper numbering sequence
    const year = new Date().getFullYear();
    const timestamp = Date.now().toString().slice(-6);
    return `GL-${year}-${timestamp}`;
  }

  /**
   * Generate GL lines based on posting rules
   */
  private async generateGlLines(context: PostingContext, glTransactionId: string): Promise<GlTransactionLine[]> {
    const glLines: GlTransactionLine[] = [];
    let lineNumber = 1;

    // Sort posting rules by sequence number
    const sortedRules = context.postingRules.sort((a, b) => a.sequenceNumber - b.sequenceNumber);

    for (const rule of sortedRules) {
      const applicableLines = this.getApplicableLines(context.businessTransactionLines, rule);
      
      for (const businessLine of applicableLines) {
        const ruleLines = await this.applyPostingRule(
          rule,
          businessLine,
          context.businessTransaction,
          glTransactionId,
          lineNumber
        );
        
        glLines.push(...ruleLines);
        lineNumber += ruleLines.length;
      }
    }

    return glLines;
  }

  /**
   * Get business transaction lines that match the posting rule criteria
   */
  private getApplicableLines(businessLines: BusinessTransactionLine[], rule: GlPostingRule): BusinessTransactionLine[] {
    return businessLines.filter(line => {
      // If rule specifies line type, filter by it
      if (rule.lineType && line.lineType !== rule.lineType) {
        return false;
      }

      // TODO: Apply conditionSql if specified
      // This would evaluate SQL expressions like "line_amount > 1000"
      
      return true;
    });
  }

  /**
   * Apply a single posting rule to create GL lines
   */
  private async applyPostingRule(
    rule: GlPostingRule,
    businessLine: BusinessTransactionLine,
    businessTransaction: BusinessTransaction,
    glTransactionId: string,
    startingLineNumber: number
  ): Promise<GlTransactionLine[]> {
    const glLines: GlTransactionLine[] = [];
    
    // Calculate amount based on formula
    const amount = this.calculateAmount(rule.amountFormula || 'line_amount', businessLine);
    
    // Apply exchange rate
    const exchangeRate = Number(businessTransaction.exchangeRate || 1);
    const baseAmount = amount * exchangeRate;
    
    // Create debit line if debit account specified
    if (rule.debitAccountId) {
      const debitLine: CreateGlTransactionLineInput = {
        transactionId: glTransactionId,
        lineNumber: startingLineNumber,
        accountId: rule.debitAccountId,
        classId: businessLine.classId,
        departmentId: businessLine.departmentId,
        locationId: businessLine.locationId,
        subsidiaryId: businessTransaction.subsidiaryId,
        debitAmount: amount.toString(),
        creditAmount: '0',
        currencyCode: businessTransaction.currencyCode,
        exchangeRate: exchangeRate.toString(),
        baseDebitAmount: baseAmount.toString(),
        baseCreditAmount: '0',
        description: this.generateLineDescription(rule.descriptionTemplate, businessLine, businessTransaction),
        reference1: businessTransaction.transactionNumber,
        reference2: businessLine.description,
        projectId: businessLine.projectId,
      };

      glLines.push({
        ...debitLine,
        id: `gl-line-${Date.now()}-${startingLineNumber}`,
        createdDate: new Date(),
      } as GlTransactionLine);
    }

    // Create credit line if credit account specified
    if (rule.creditAccountId) {
      const creditLine: CreateGlTransactionLineInput = {
        transactionId: glTransactionId,
        lineNumber: startingLineNumber + 1,
        accountId: rule.creditAccountId,
        classId: businessLine.classId,
        departmentId: businessLine.departmentId,
        locationId: businessLine.locationId,
        subsidiaryId: businessTransaction.subsidiaryId,
        debitAmount: '0',
        creditAmount: amount.toString(),
        currencyCode: businessTransaction.currencyCode,
        exchangeRate: exchangeRate.toString(),
        baseDebitAmount: '0',
        baseCreditAmount: baseAmount.toString(),
        description: this.generateLineDescription(rule.descriptionTemplate, businessLine, businessTransaction),
        reference1: businessTransaction.transactionNumber,
        reference2: businessLine.description,
        projectId: businessLine.projectId,
      };

      glLines.push({
        ...creditLine,
        id: `gl-line-${Date.now()}-${startingLineNumber + 1}`,
        createdDate: new Date(),
      } as GlTransactionLine);
    }

    return glLines;
  }

  /**
   * Calculate amount based on formula
   */
  private calculateAmount(formula: string, businessLine: BusinessTransactionLine): number {
    // Simple formula evaluator - in production, this would be more sophisticated
    switch (formula.toLowerCase()) {
      case 'line_amount':
        return Number(businessLine.lineAmount || 0);
      case 'tax_amount':
        return Number(businessLine.taxAmount || 0);
      case 'cost_amount':
        return Number(businessLine.costAmount || 0);
      case 'discount_amount':
        return Number(businessLine.discountAmount || 0);
      default:
        // TODO: Implement expression evaluator for complex formulas
        return Number(businessLine.lineAmount || 0);
    }
  }

  /**
   * Generate GL line description from template
   */
  private generateLineDescription(
    template: string | undefined,
    businessLine: BusinessTransactionLine,
    businessTransaction: BusinessTransaction
  ): string {
    if (!template) {
      return businessLine.description || 'Auto-posted transaction';
    }

    // Simple template replacement - in production, this would be more sophisticated
    return template
      .replace('{line.description}', businessLine.description || '')
      .replace('{transaction.number}', businessTransaction.transactionNumber || '')
      .replace('{transaction.memo}', businessTransaction.memo || '')
      .replace('{line.itemId}', businessLine.itemId || '');
  }

  /**
   * Validate that GL transaction is balanced
   */
  private validateGlBalance(glLines: GlTransactionLine[]): void {
    let totalDebits = 0;
    let totalCredits = 0;

    for (const line of glLines) {
      totalDebits += Number(line.debitAmount || 0);
      totalCredits += Number(line.creditAmount || 0);
    }

    const difference = Math.abs(totalDebits - totalCredits);
    if (difference > 0.01) { // Allow for minor rounding differences
      throw new ServiceError(
        `GL transaction is not balanced. Debits: ${totalDebits}, Credits: ${totalCredits}`,
        'GL_TRANSACTION_NOT_BALANCED',
        400
      );
    }
  }

  /**
   * Calculate account balance updates from GL lines
   */
  private calculateBalanceUpdates(
    glLines: GlTransactionLine[],
    context: PostingContext
  ): AccountBalanceUpdate[] {
    const balanceMap = new Map<string, AccountBalanceUpdate>();

    for (const line of glLines) {
      // Create unique key for account/subsidiary/period/dimensions combination
      const key = [
        line.accountId,
        line.subsidiaryId,
        context.periodId,
        line.classId || '',
        line.departmentId || '',
        line.locationId || '',
        line.currencyCode
      ].join('|');

      let balance = balanceMap.get(key);
      if (!balance) {
        balance = {
          accountId: line.accountId,
          subsidiaryId: line.subsidiaryId,
          periodId: context.periodId,
          classId: line.classId,
          departmentId: line.departmentId,
          locationId: line.locationId,
          currencyCode: line.currencyCode,
          debitAmount: 0,
          creditAmount: 0,
        };
        balanceMap.set(key, balance);
      }

      balance.debitAmount += Number(line.baseDebitAmount || 0);
      balance.creditAmount += Number(line.baseCreditAmount || 0);
    }

    return Array.from(balanceMap.values());
  }

  /**
   * Post GL entries and update balances
   */
  async postGlEntries(postingResult: PostingResult): Promise<void> {
    const organizationId = this.requireOrganizationContext();
    
    // TODO: Implement database operations in transaction
    // 1. Create GL transaction
    // 2. Create GL lines
    // 3. Update account balances
    // 4. Update business transaction status
    
    throw new ServiceError(
      'GL posting not yet implemented',
      'NOT_IMPLEMENTED',
      501
    );
  }

  /**
   * Reverse GL entries
   */
  async reverseGlEntries(
    originalGlTransactionId: string,
    reversalReason: string,
    reversalDate: Date = new Date()
  ): Promise<PostingResult> {
    const organizationId = this.requireOrganizationContext();
    const userId = this.requireUserContext();
    
    // TODO: Implement GL reversal logic
    // 1. Get original GL transaction and lines
    // 2. Create reversing GL transaction
    // 3. Create reversing GL lines (swap debit/credit)
    // 4. Update account balances
    // 5. Mark original transaction as reversed
    
    throw new ServiceError(
      'GL reversal not yet implemented',
      'NOT_IMPLEMENTED',
      501
    );
  }
}