import { BaseService } from './base-service';
import {
  GlTransaction,
  GlTransactionLine,
  PaginationParams,
  PaginatedResult,
  ServiceError,
  ServiceContext,
} from '../types';
import { db as globalDb, type ContextualDatabase, GlReportingRepository } from '@glapi/database';
import type {
  GlTransactionPaginationParams,
  GlTransactionFilters,
  AccountActivityFilters,
  TrialBalanceFilters
} from '@glapi/database';

export interface GlReportingServiceOptions {
  db?: ContextualDatabase;
}

export interface TrialBalanceRequest {
  subsidiaryId?: string;
  periodId: string;
  includeInactive?: boolean;
  classId?: string;
  departmentId?: string;
  locationId?: string;
}

export interface TrialBalanceEntry {
  accountId: string;
  accountNumber: string;
  accountName: string;
  accountType: string;
  debitBalance: number;
  creditBalance: number;
  netBalance: number;
  periodActivity: {
    debits: number;
    credits: number;
    net: number;
  };
  ytdActivity: {
    debits: number;
    credits: number;
    net: number;
  };
}

export interface TrialBalanceReport {
  periodName: string;
  subsidiaryName: string;
  asOfDate: string;
  entries: TrialBalanceEntry[];
  totals: {
    totalDebits: number;
    totalCredits: number;
    difference: number;
  };
}

export interface AccountActivityRequest {
  accountId: string;
  subsidiaryId?: string;
  dateFrom: string | Date;
  dateTo: string | Date;
  classId?: string;
  departmentId?: string;
  locationId?: string;
}

export interface AccountActivityEntry {
  date: string;
  transactionNumber: string;
  description: string;
  reference: string;
  debitAmount: number;
  creditAmount: number;
  runningBalance: number;
  glTransactionId: string;
  sourceTransactionId?: string;
}

export interface GeneralLedgerRequest {
  subsidiaryId?: string;
  periodId?: string;
  dateFrom?: string | Date;
  dateTo?: string | Date;
  accountIds?: string[];
  includeAdjustments?: boolean;
  groupBy?: 'account' | 'date' | 'transaction';
}

export interface GeneralLedgerEntry {
  glTransactionId: string;
  transactionNumber: string;
  transactionDate: string;
  postingDate: string;
  description: string;
  accountId: string;
  accountNumber: string;
  accountName: string;
  debitAmount: number;
  creditAmount: number;
  reference1?: string;
  reference2?: string;
  classId?: string;
  departmentId?: string;
  locationId?: string;
}

export class GlReportingService extends BaseService {
  private db: ContextualDatabase;
  private repository: GlReportingRepository;

  constructor(context: ServiceContext = {}, options: GlReportingServiceOptions = {}) {
    super(context);
    this.db = options.db ?? globalDb;
    this.repository = new GlReportingRepository(this.db);
  }

  /**
   * Transform database GL transaction to service layer type
   */
  private transformGlTransaction(dbTransaction: any): GlTransaction {
    return {
      id: dbTransaction.id,
      transactionNumber: dbTransaction.transactionNumber,
      subsidiaryId: dbTransaction.subsidiaryId,
      periodId: dbTransaction.periodId,
      transactionDate: dbTransaction.transactionDate,
      postingDate: dbTransaction.postingDate,
      transactionType: dbTransaction.transactionType as 'JOURNAL' | 'POSTING' | 'REVERSAL' | 'CLOSING',
      sourceTransactionId: dbTransaction.sourceTransactionId || undefined,
      description: dbTransaction.description || '',
      totalDebitAmount: dbTransaction.totalDebitAmount,
      totalCreditAmount: dbTransaction.totalCreditAmount,
      baseCurrencyCode: dbTransaction.currencyCode,
      status: dbTransaction.status,
      reversedByTransactionId: dbTransaction.reversalTransactionId || undefined,
      createdBy: dbTransaction.createdBy || undefined,
      createdDate: dbTransaction.createdDate || undefined,
      modifiedBy: dbTransaction.modifiedBy || undefined,
      modifiedDate: dbTransaction.modifiedDate || undefined,
      autoGenerated: dbTransaction.autoGenerated !== undefined ? dbTransaction.autoGenerated : false,
      versionNumber: dbTransaction.versionNumber !== undefined ? dbTransaction.versionNumber : 1,
    };
  }

  /**
   * Generate trial balance report
   */
  async getTrialBalance(request: TrialBalanceRequest): Promise<TrialBalanceReport> {
    const organizationId = this.requireOrganizationContext();
    
    // Validate request
    if (!request.periodId) {
      throw new ServiceError(
        'Period ID is required for trial balance',
        'MISSING_PERIOD_ID',
        400
      );
    }

    try {
      const filters: TrialBalanceFilters = {
        periodId: request.periodId,
        subsidiaryId: request.subsidiaryId,
        includeInactive: request.includeInactive,
        classId: request.classId,
        departmentId: request.departmentId,
        locationId: request.locationId,
      };
      
      const result = await this.repository.getTrialBalance(filters, organizationId);
      
      return {
        periodName: result.periodName,
        subsidiaryName: result.subsidiaryName,
        asOfDate: result.asOfDate,
        entries: result.entries,
        totals: result.totals,
      };
    } catch (error) {
      throw new ServiceError(
        `Failed to generate trial balance: ${error instanceof Error ? error.message : String(error)}`,
        'TRIAL_BALANCE_FAILED',
        500
      );
    }
  }

  /**
   * Get account activity (account ledger)
   */
  async getAccountActivity(
    request: AccountActivityRequest,
    params: PaginationParams = {}
  ): Promise<PaginatedResult<AccountActivityEntry>> {
    const organizationId = this.requireOrganizationContext();
    
    // Validate request
    if (!request.accountId) {
      throw new ServiceError(
        'Account ID is required',
        'MISSING_ACCOUNT_ID',
        400
      );
    }

    if (!request.dateFrom || !request.dateTo) {
      throw new ServiceError(
        'Date range is required',
        'MISSING_DATE_RANGE',
        400
      );
    }

    try {
      const filters: AccountActivityFilters = {
        accountId: request.accountId,
        subsidiaryId: request.subsidiaryId,
        dateFrom: request.dateFrom,
        dateTo: request.dateTo,
        classId: request.classId,
        departmentId: request.departmentId,
        locationId: request.locationId,
      };
      
      const result = await this.repository.getAccountActivity(
        filters,
        organizationId,
        {
          page: params.page,
          limit: params.limit,
        }
      );
      
      return {
        data: result.data.map(entry => ({
          date: entry.date,
          transactionNumber: entry.transactionNumber,
          description: entry.description || '',
          reference: entry.reference || '',
          debitAmount: entry.debitAmount,
          creditAmount: entry.creditAmount,
          runningBalance: entry.runningBalance,
          glTransactionId: entry.glTransactionId,
          sourceTransactionId: entry.sourceTransactionId || undefined,
        })),
        total: result.total,
        page: result.page,
        limit: result.limit,
        totalPages: result.totalPages,
      };
    } catch (error) {
      throw new ServiceError(
        `Failed to get account activity: ${error instanceof Error ? error.message : String(error)}`,
        'ACCOUNT_ACTIVITY_FAILED',
        500
      );
    }
  }

  /**
   * Get general ledger entries
   */
  async getGeneralLedger(
    request: GeneralLedgerRequest,
    params: PaginationParams = {}
  ): Promise<PaginatedResult<GeneralLedgerEntry>> {
    const organizationId = this.requireOrganizationContext();
    
    try {
      const filters = {
        subsidiaryId: request.subsidiaryId,
        periodId: request.periodId,
        dateFrom: request.dateFrom,
        dateTo: request.dateTo,
        accountIds: request.accountIds,
        includeAdjustments: request.includeAdjustments,
        groupBy: request.groupBy,
      };
      
      const result = await this.repository.getGeneralLedger(
        filters,
        organizationId,
        {
          page: params.page,
          limit: params.limit,
        }
      );
      
      return {
        data: result.data.map(entry => ({
          glTransactionId: entry.glTransactionId,
          transactionNumber: entry.transactionNumber,
          transactionDate: entry.transactionDate,
          postingDate: entry.postingDate,
          description: entry.description || '',
          accountId: entry.accountId,
          accountNumber: entry.accountNumber,
          accountName: entry.accountName,
          debitAmount: entry.debitAmount,
          creditAmount: entry.creditAmount,
          reference1: entry.reference1 || undefined,
          reference2: entry.reference2 || undefined,
          classId: entry.classId || undefined,
          departmentId: entry.departmentId || undefined,
          locationId: entry.locationId || undefined,
        })),
        total: result.total,
        page: result.page,
        limit: result.limit,
        totalPages: result.totalPages,
      };
    } catch (error) {
      throw new ServiceError(
        `Failed to get general ledger: ${error instanceof Error ? error.message : String(error)}`,
        'GENERAL_LEDGER_FAILED',
        500
      );
    }
  }

  /**
   * Get GL transaction details
   */
  async getGlTransactionById(id: string): Promise<GlTransaction | null> {
    const organizationId = this.requireOrganizationContext();
    
    try {
      const result = await this.repository.findGlTransactionById(id, organizationId);
      
      if (!result) {
        return null;
      }
      
      return this.transformGlTransaction(result);
    } catch (error) {
      throw new ServiceError(
        `Failed to get GL transaction: ${error instanceof Error ? error.message : String(error)}`,
        'GL_TRANSACTION_RETRIEVAL_FAILED',
        500
      );
    }
  }

  /**
   * Get GL transaction lines
   */
  async getGlTransactionLines(transactionId: string): Promise<GlTransactionLine[]> {
    const organizationId = this.requireOrganizationContext();
    
    try {
      const result = await this.repository.getGlTransactionLines(transactionId, organizationId);
      
      return result.map(line => ({
        id: line.id,
        transactionId: line.transactionId,
        lineNumber: line.lineNumber,
        accountId: line.accountId,
        subsidiaryId: line.subsidiaryId,
        classId: line.classId || undefined,
        departmentId: line.departmentId || undefined,
        locationId: line.locationId || undefined,
        debitAmount: line.debitAmount,
        creditAmount: line.creditAmount,
        currencyCode: line.currencyCode,
        exchangeRate: line.exchangeRate,
        baseDebitAmount: line.baseDebitAmount,
        baseCreditAmount: line.baseCreditAmount,
        memo: '',
        entityId: undefined,
        entityType: undefined,
        createdBy: undefined,
        createdDate: line.createdDate,
        modifiedDate: undefined,
      }));
    } catch (error) {
      throw new ServiceError(
        `Failed to get GL transaction lines: ${error instanceof Error ? error.message : String(error)}`,
        'GL_TRANSACTION_LINES_FAILED',
        500
      );
    }
  }

  /**
   * List GL transactions
   */
  async listGlTransactions(
    params: PaginationParams = {},
    filters: {
      subsidiaryId?: string;
      periodId?: string;
      status?: string;
      transactionType?: string;
      dateFrom?: string | Date;
      dateTo?: string | Date;
      sourceTransactionId?: string;
    } = {}
  ): Promise<PaginatedResult<GlTransaction>> {
    const organizationId = this.requireOrganizationContext();
    
    try {
      const paginationParams: GlTransactionPaginationParams = {
        page: params.page,
        limit: params.limit,
        orderBy: 'transactionDate',
        orderDirection: 'desc',
      };
      
      const glFilters: GlTransactionFilters = {
        subsidiaryId: filters.subsidiaryId,
        periodId: filters.periodId,
        status: filters.status,
        transactionType: filters.transactionType,
        dateFrom: filters.dateFrom,
        dateTo: filters.dateTo,
        sourceTransactionId: filters.sourceTransactionId,
      };
      
      const result = await this.repository.findAllGlTransactions(
        organizationId,
        paginationParams,
        glFilters
      );
      
      return {
        data: result.data.map(tx => this.transformGlTransaction(tx)),
        total: result.total,
        page: result.page,
        limit: result.limit,
        totalPages: result.totalPages,
      };
    } catch (error) {
      throw new ServiceError(
        `Failed to list GL transactions: ${error instanceof Error ? error.message : String(error)}`,
        'GL_TRANSACTIONS_LIST_FAILED',
        500
      );
    }
  }

  /**
   * Get account balances for a period
   */
  async getAccountBalances(
    periodId: string,
    subsidiaryId?: string,
    accountIds?: string[]
  ): Promise<any[]> {
    const organizationId = this.requireOrganizationContext();
    
    // TODO: Implement account balance query
    // 1. Get account balances for period
    // 2. Filter by subsidiary if specified
    // 3. Filter by account IDs if specified
    
    throw new ServiceError(
      'Get account balances not yet implemented',
      'NOT_IMPLEMENTED',
      501
    );
  }

  /**
   * Get period summary (totals, counts, etc.)
   */
  async getPeriodSummary(periodId: string, subsidiaryId?: string): Promise<any> {
    const organizationId = this.requireOrganizationContext();
    
    // TODO: Implement period summary
    // 1. Count GL transactions for period
    // 2. Sum debits and credits
    // 3. Count by transaction type
    // 4. Get period dates and status
    
    throw new ServiceError(
      'Get period summary not yet implemented',
      'NOT_IMPLEMENTED',
      501
    );
  }

  /**
   * Validate GL integrity for a period
   */
  async validateGlIntegrity(periodId: string, subsidiaryId?: string): Promise<{
    isBalanced: boolean;
    totalDebits: number;
    totalCredits: number;
    difference: number;
    issues: string[];
  }> {
    const organizationId = this.requireOrganizationContext();
    
    // TODO: Implement GL integrity validation
    // 1. Sum all debits and credits for the period
    // 2. Check that transactions are balanced
    // 3. Verify account balance rollups match line details
    // 4. Check for orphaned lines or missing accounts
    
    throw new ServiceError(
      'GL integrity validation not yet implemented',
      'NOT_IMPLEMENTED',
      501
    );
  }
}