/**
 * Inventory GL Posting Service
 *
 * Handles GL journal entry generation for inventory adjustments and transfers.
 * Creates double-entry accounting entries following GAAP:
 *
 * Inventory Adjustments:
 * - Quantity Increase: Dr Inventory, Cr Adjustment Account (shrinkage recovery)
 * - Quantity Decrease: Dr Adjustment Account, Cr Inventory (shrinkage/loss)
 * - Write-off: Dr Write-off Expense, Cr Inventory
 * - Value Revaluation: Dr/Cr Inventory, Cr/Dr Revaluation Reserve
 *
 * Inventory Transfers:
 * - Intra-subsidiary: Dr Destination Location Inventory, Cr Source Location Inventory
 * - Inter-subsidiary (at ship): Dr Inventory in Transit, Cr Source Inventory
 * - Inter-subsidiary (at receive): Dr Destination Inventory, Cr Inventory in Transit
 */

import { eq, and } from 'drizzle-orm';
import {
  glTransactions,
  glTransactionLines,
  inventoryAdjustments,
  inventoryAdjustmentLines,
  inventoryTransfers,
  inventoryTransferLines,
  accountingPeriods,
  type InsertGlTransaction,
  type InsertGlTransactionLine,
} from '@glapi/database';
import { getDb } from '@glapi/database';
import { DatabaseType } from '@glapi/database';
import { sql } from 'drizzle-orm';

// Service context
export interface InventoryGlPostingContext {
  organizationId: string;
  userId?: string;
  baseCurrencyCode?: string;
}

// GL Transaction result
export interface GlPostingResult {
  glTransactionId: string;
  transactionNumber: string;
  totalDebits: number;
  totalCredits: number;
  lineCount: number;
}

// Default accounts (would typically come from organization settings)
export interface InventoryAccountConfig {
  inventoryAssetAccountId: string;
  adjustmentExpenseAccountId: string;
  writeOffExpenseAccountId: string;
  revaluationReserveAccountId: string;
  transitInventoryAccountId: string;
  intercompanyReceivableAccountId?: string;
  intercompanyPayableAccountId?: string;
}

export class InventoryGlPostingService {
  private db: DatabaseType;
  private context: InventoryGlPostingContext;

  constructor(context: InventoryGlPostingContext) {
    this.db = getDb();
    this.context = context;
  }

  /**
   * Post inventory adjustment to GL
   */
  async postAdjustment(
    adjustmentId: string,
    accountConfig: InventoryAccountConfig
  ): Promise<GlPostingResult> {
    // Get adjustment with lines
    const [adjustment] = await this.db
      .select()
      .from(inventoryAdjustments)
      .where(
        and(
          eq(inventoryAdjustments.id, adjustmentId),
          eq(inventoryAdjustments.organizationId, this.context.organizationId)
        )
      );

    if (!adjustment) {
      throw new Error(`Adjustment ${adjustmentId} not found`);
    }

    if (adjustment.status !== 'APPROVED') {
      throw new Error('Adjustment must be approved before posting to GL');
    }

    const lines = await this.db
      .select()
      .from(inventoryAdjustmentLines)
      .where(eq(inventoryAdjustmentLines.adjustmentId, adjustmentId));

    if (lines.length === 0) {
      throw new Error('Adjustment has no lines to post');
    }

    // Get accounting period for the adjustment date
    const periodId = await this.getAccountingPeriod(
      adjustment.subsidiaryId,
      adjustment.adjustmentDate
    );

    // Generate GL transaction number
    const transactionNumber = await this.generateGlTransactionNumber('ADJ');

    // Create GL transaction
    const [glTransaction] = await this.db
      .insert(glTransactions)
      .values({
        transactionNumber,
        subsidiaryId: adjustment.subsidiaryId,
        transactionDate: adjustment.adjustmentDate,
        postingDate: new Date().toISOString().split('T')[0],
        periodId,
        transactionType: 'POSTING',
        sourceSystem: 'INVENTORY',
        sourceTransactionId: adjustmentId,
        sourceTransactionType: 'INVENTORY_ADJUSTMENT',
        description: `Inventory Adjustment: ${adjustment.adjustmentNumber}`,
        referenceNumber: adjustment.reference,
        baseCurrencyCode: this.context.baseCurrencyCode ?? 'USD',
        totalDebitAmount: '0',
        totalCreditAmount: '0',
        status: 'POSTED',
        autoGenerated: true,
        createdBy: this.context.userId,
        postedBy: this.context.userId,
        postedDate: new Date(),
      } as InsertGlTransaction)
      .returning();

    // Create GL lines for each adjustment line
    let lineNumber = 1;
    let totalDebits = 0;
    let totalCredits = 0;

    for (const line of lines) {
      const adjustmentValue = Math.abs(Number(line.adjustmentValue || 0));
      if (adjustmentValue === 0) continue;

      const inventoryAccountId = line.inventoryAccountId ?? accountConfig.inventoryAssetAccountId;
      let offsetAccountId: string;

      // Determine offset account based on adjustment type
      switch (adjustment.adjustmentType) {
        case 'WRITE_OFF':
          offsetAccountId = accountConfig.writeOffExpenseAccountId;
          break;
        case 'VALUE_REVALUATION':
          offsetAccountId = accountConfig.revaluationReserveAccountId;
          break;
        case 'WRITE_DOWN':
          offsetAccountId = line.adjustmentAccountId ?? accountConfig.writeOffExpenseAccountId;
          break;
        default:
          offsetAccountId = line.adjustmentAccountId ?? accountConfig.adjustmentExpenseAccountId;
      }

      // Determine debit/credit based on adjustment type and value
      const isIncrease =
        adjustment.adjustmentType === 'QUANTITY_INCREASE' ||
        (adjustment.adjustmentType === 'VALUE_REVALUATION' &&
          Number(line.adjustmentValue || 0) > 0);

      if (isIncrease) {
        // Inventory increases: Dr Inventory, Cr Offset
        await this.createGlLine(
          glTransaction.id,
          lineNumber++,
          inventoryAccountId,
          adjustment.subsidiaryId,
          adjustmentValue,
          0,
          `${adjustment.adjustmentType}: ${line.itemId}`
        );
        totalDebits += adjustmentValue;

        await this.createGlLine(
          glTransaction.id,
          lineNumber++,
          offsetAccountId,
          adjustment.subsidiaryId,
          0,
          adjustmentValue,
          `${adjustment.adjustmentType}: ${line.itemId}`
        );
        totalCredits += adjustmentValue;
      } else {
        // Inventory decreases: Dr Offset, Cr Inventory
        await this.createGlLine(
          glTransaction.id,
          lineNumber++,
          offsetAccountId,
          adjustment.subsidiaryId,
          adjustmentValue,
          0,
          `${adjustment.adjustmentType}: ${line.itemId}`
        );
        totalDebits += adjustmentValue;

        await this.createGlLine(
          glTransaction.id,
          lineNumber++,
          inventoryAccountId,
          adjustment.subsidiaryId,
          0,
          adjustmentValue,
          `${adjustment.adjustmentType}: ${line.itemId}`
        );
        totalCredits += adjustmentValue;
      }
    }

    // Update GL transaction totals
    await this.db
      .update(glTransactions)
      .set({
        totalDebitAmount: String(totalDebits),
        totalCreditAmount: String(totalCredits),
      })
      .where(eq(glTransactions.id, glTransaction.id));

    // Update adjustment with GL transaction reference
    await this.db
      .update(inventoryAdjustments)
      .set({
        glTransactionId: glTransaction.id,
        postedAt: new Date(),
        updatedAt: new Date(),
      })
      .where(eq(inventoryAdjustments.id, adjustmentId));

    return {
      glTransactionId: glTransaction.id,
      transactionNumber,
      totalDebits,
      totalCredits,
      lineCount: lineNumber - 1,
    };
  }

  /**
   * Post inventory transfer shipment to GL
   * Creates: Dr Inventory in Transit, Cr Source Inventory
   */
  async postTransferShipment(
    transferId: string,
    accountConfig: InventoryAccountConfig
  ): Promise<GlPostingResult> {
    const [transfer] = await this.db
      .select()
      .from(inventoryTransfers)
      .where(
        and(
          eq(inventoryTransfers.id, transferId),
          eq(inventoryTransfers.organizationId, this.context.organizationId)
        )
      );

    if (!transfer) {
      throw new Error(`Transfer ${transferId} not found`);
    }

    const lines = await this.db
      .select()
      .from(inventoryTransferLines)
      .where(eq(inventoryTransferLines.transferId, transferId));

    if (lines.length === 0) {
      throw new Error('Transfer has no lines to post');
    }

    const periodId = await this.getAccountingPeriod(
      transfer.fromSubsidiaryId,
      transfer.actualShipDate ?? transfer.transferDate
    );

    const transactionNumber = await this.generateGlTransactionNumber('TRF-SHIP');

    const [glTransaction] = await this.db
      .insert(glTransactions)
      .values({
        transactionNumber,
        subsidiaryId: transfer.fromSubsidiaryId,
        transactionDate: transfer.actualShipDate ?? transfer.transferDate,
        postingDate: new Date().toISOString().split('T')[0],
        periodId,
        transactionType: 'POSTING',
        sourceSystem: 'INVENTORY',
        sourceTransactionId: transferId,
        sourceTransactionType: 'INVENTORY_TRANSFER_SHIP',
        description: `Inventory Transfer Shipment: ${transfer.transferNumber}`,
        referenceNumber: transfer.reference,
        baseCurrencyCode: this.context.baseCurrencyCode ?? 'USD',
        totalDebitAmount: '0',
        totalCreditAmount: '0',
        status: 'POSTED',
        autoGenerated: true,
        createdBy: this.context.userId,
        postedBy: this.context.userId,
        postedDate: new Date(),
      } as InsertGlTransaction)
      .returning();

    let lineNumber = 1;
    let totalDebits = 0;
    let totalCredits = 0;

    for (const line of lines) {
      const shippedQty = Number(line.quantityShipped || 0);
      const unitCost = Number(line.unitCost || 0);
      const transferValue = shippedQty * unitCost;

      if (transferValue === 0) continue;

      const fromInventoryAccount = line.fromInventoryAccountId ?? accountConfig.inventoryAssetAccountId;
      const transitAccount = line.transitAccountId ?? accountConfig.transitInventoryAccountId;

      // Dr Inventory in Transit
      await this.createGlLine(
        glTransaction.id,
        lineNumber++,
        transitAccount,
        transfer.fromSubsidiaryId,
        transferValue,
        0,
        `Transfer out: ${line.itemId} to ${transfer.toSubsidiaryId}`
      );
      totalDebits += transferValue;

      // Cr Source Inventory
      await this.createGlLine(
        glTransaction.id,
        lineNumber++,
        fromInventoryAccount,
        transfer.fromSubsidiaryId,
        0,
        transferValue,
        `Transfer out: ${line.itemId}`
      );
      totalCredits += transferValue;
    }

    // Update totals
    await this.db
      .update(glTransactions)
      .set({
        totalDebitAmount: String(totalDebits),
        totalCreditAmount: String(totalCredits),
      })
      .where(eq(glTransactions.id, glTransaction.id));

    // Update transfer with shipment GL reference
    await this.db
      .update(inventoryTransfers)
      .set({
        shipGlTransactionId: glTransaction.id,
        updatedAt: new Date(),
      })
      .where(eq(inventoryTransfers.id, transferId));

    return {
      glTransactionId: glTransaction.id,
      transactionNumber,
      totalDebits,
      totalCredits,
      lineCount: lineNumber - 1,
    };
  }

  /**
   * Post inventory transfer receipt to GL
   * Creates: Dr Destination Inventory, Cr Inventory in Transit
   * For intercompany: also creates intercompany entries
   */
  async postTransferReceipt(
    transferId: string,
    accountConfig: InventoryAccountConfig
  ): Promise<GlPostingResult> {
    const [transfer] = await this.db
      .select()
      .from(inventoryTransfers)
      .where(
        and(
          eq(inventoryTransfers.id, transferId),
          eq(inventoryTransfers.organizationId, this.context.organizationId)
        )
      );

    if (!transfer) {
      throw new Error(`Transfer ${transferId} not found`);
    }

    const lines = await this.db
      .select()
      .from(inventoryTransferLines)
      .where(eq(inventoryTransferLines.transferId, transferId));

    if (lines.length === 0) {
      throw new Error('Transfer has no lines to post');
    }

    const periodId = await this.getAccountingPeriod(
      transfer.toSubsidiaryId,
      transfer.actualReceiveDate ?? transfer.transferDate
    );

    const transactionNumber = await this.generateGlTransactionNumber('TRF-RCV');

    const [glTransaction] = await this.db
      .insert(glTransactions)
      .values({
        transactionNumber,
        subsidiaryId: transfer.toSubsidiaryId,
        transactionDate: transfer.actualReceiveDate ?? transfer.transferDate,
        postingDate: new Date().toISOString().split('T')[0],
        periodId,
        transactionType: 'POSTING',
        sourceSystem: 'INVENTORY',
        sourceTransactionId: transferId,
        sourceTransactionType: 'INVENTORY_TRANSFER_RECEIVE',
        description: `Inventory Transfer Receipt: ${transfer.transferNumber}`,
        referenceNumber: transfer.reference,
        baseCurrencyCode: this.context.baseCurrencyCode ?? 'USD',
        totalDebitAmount: '0',
        totalCreditAmount: '0',
        status: 'POSTED',
        autoGenerated: true,
        createdBy: this.context.userId,
        postedBy: this.context.userId,
        postedDate: new Date(),
      } as InsertGlTransaction)
      .returning();

    let lineNumber = 1;
    let totalDebits = 0;
    let totalCredits = 0;

    for (const line of lines) {
      const receivedQty = Number(line.quantityReceived || 0);
      // For intercompany, use transfer price; otherwise use cost
      const unitValue = transfer.isIntercompany
        ? Number(line.transferUnitPrice || line.unitCost || 0)
        : Number(line.unitCost || 0);
      const transferValue = receivedQty * unitValue;

      if (transferValue === 0) continue;

      const toInventoryAccount = line.toInventoryAccountId ?? accountConfig.inventoryAssetAccountId;
      const transitAccount = line.transitAccountId ?? accountConfig.transitInventoryAccountId;

      // Dr Destination Inventory
      await this.createGlLine(
        glTransaction.id,
        lineNumber++,
        toInventoryAccount,
        transfer.toSubsidiaryId,
        transferValue,
        0,
        `Transfer in: ${line.itemId} from ${transfer.fromSubsidiaryId}`
      );
      totalDebits += transferValue;

      // Cr Inventory in Transit
      await this.createGlLine(
        glTransaction.id,
        lineNumber++,
        transitAccount,
        transfer.toSubsidiaryId,
        0,
        transferValue,
        `Transfer in: ${line.itemId}`
      );
      totalCredits += transferValue;

      // Handle intercompany markup/markdown if applicable
      if (transfer.isIntercompany) {
        const costValue = receivedQty * Number(line.unitCost || 0);
        const markup = transferValue - costValue;

        if (markup !== 0 && accountConfig.intercompanyReceivableAccountId && accountConfig.intercompanyPayableAccountId) {
          // Record intercompany profit/loss elimination entries
          // This would typically be handled in consolidation
        }
      }
    }

    // Update totals
    await this.db
      .update(glTransactions)
      .set({
        totalDebitAmount: String(totalDebits),
        totalCreditAmount: String(totalCredits),
      })
      .where(eq(glTransactions.id, glTransaction.id));

    // Update transfer with receipt GL reference
    await this.db
      .update(inventoryTransfers)
      .set({
        receiveGlTransactionId: glTransaction.id,
        postedAt: new Date(),
        updatedAt: new Date(),
      })
      .where(eq(inventoryTransfers.id, transferId));

    return {
      glTransactionId: glTransaction.id,
      transactionNumber,
      totalDebits,
      totalCredits,
      lineCount: lineNumber - 1,
    };
  }

  /**
   * Post complete transfer (for intra-subsidiary transfers that skip transit)
   */
  async postDirectTransfer(
    transferId: string,
    accountConfig: InventoryAccountConfig
  ): Promise<GlPostingResult> {
    const [transfer] = await this.db
      .select()
      .from(inventoryTransfers)
      .where(
        and(
          eq(inventoryTransfers.id, transferId),
          eq(inventoryTransfers.organizationId, this.context.organizationId)
        )
      );

    if (!transfer) {
      throw new Error(`Transfer ${transferId} not found`);
    }

    // For same-subsidiary transfers, we can do a direct entry
    if (transfer.fromSubsidiaryId !== transfer.toSubsidiaryId) {
      throw new Error('Direct transfer only allowed for intra-subsidiary transfers');
    }

    const lines = await this.db
      .select()
      .from(inventoryTransferLines)
      .where(eq(inventoryTransferLines.transferId, transferId));

    if (lines.length === 0) {
      throw new Error('Transfer has no lines to post');
    }

    const periodId = await this.getAccountingPeriod(
      transfer.fromSubsidiaryId,
      transfer.transferDate
    );

    const transactionNumber = await this.generateGlTransactionNumber('TRF');

    const [glTransaction] = await this.db
      .insert(glTransactions)
      .values({
        transactionNumber,
        subsidiaryId: transfer.fromSubsidiaryId,
        transactionDate: transfer.transferDate,
        postingDate: new Date().toISOString().split('T')[0],
        periodId,
        transactionType: 'POSTING',
        sourceSystem: 'INVENTORY',
        sourceTransactionId: transferId,
        sourceTransactionType: 'INVENTORY_TRANSFER',
        description: `Inventory Transfer: ${transfer.transferNumber}`,
        referenceNumber: transfer.reference,
        baseCurrencyCode: this.context.baseCurrencyCode ?? 'USD',
        totalDebitAmount: '0',
        totalCreditAmount: '0',
        status: 'POSTED',
        autoGenerated: true,
        createdBy: this.context.userId,
        postedBy: this.context.userId,
        postedDate: new Date(),
      } as InsertGlTransaction)
      .returning();

    let lineNumber = 1;
    let totalDebits = 0;
    let totalCredits = 0;

    for (const line of lines) {
      const transferQty = Number(line.quantityReceived || line.quantityShipped || line.quantityRequested || 0);
      const unitCost = Number(line.unitCost || 0);
      const transferValue = transferQty * unitCost;

      if (transferValue === 0) continue;

      const fromAccount = line.fromInventoryAccountId ?? accountConfig.inventoryAssetAccountId;
      const toAccount = line.toInventoryAccountId ?? accountConfig.inventoryAssetAccountId;

      // If locations have different accounts, create the entry
      if (fromAccount !== toAccount) {
        // Dr Destination
        await this.createGlLine(
          glTransaction.id,
          lineNumber++,
          toAccount,
          transfer.toSubsidiaryId,
          transferValue,
          0,
          `Transfer: ${line.itemId}`
        );
        totalDebits += transferValue;

        // Cr Source
        await this.createGlLine(
          glTransaction.id,
          lineNumber++,
          fromAccount,
          transfer.fromSubsidiaryId,
          0,
          transferValue,
          `Transfer: ${line.itemId}`
        );
        totalCredits += transferValue;
      }
      // If same account, no GL entry needed (just inventory movement)
    }

    // Update totals
    await this.db
      .update(glTransactions)
      .set({
        totalDebitAmount: String(totalDebits),
        totalCreditAmount: String(totalCredits),
      })
      .where(eq(glTransactions.id, glTransaction.id));

    // Update transfer
    await this.db
      .update(inventoryTransfers)
      .set({
        receiveGlTransactionId: glTransaction.id,
        postedAt: new Date(),
        updatedAt: new Date(),
      })
      .where(eq(inventoryTransfers.id, transferId));

    return {
      glTransactionId: glTransaction.id,
      transactionNumber,
      totalDebits,
      totalCredits,
      lineCount: lineNumber - 1,
    };
  }

  /**
   * Reverse GL entries for a cancelled or voided transaction
   */
  async reverseGlEntries(
    glTransactionId: string,
    reversalReason: string
  ): Promise<GlPostingResult> {
    const [originalTx] = await this.db
      .select()
      .from(glTransactions)
      .where(eq(glTransactions.id, glTransactionId));

    if (!originalTx) {
      throw new Error(`GL Transaction ${glTransactionId} not found`);
    }

    if (originalTx.status === 'REVERSED') {
      throw new Error('Transaction is already reversed');
    }

    const originalLines = await this.db
      .select()
      .from(glTransactionLines)
      .where(eq(glTransactionLines.transactionId, glTransactionId));

    const transactionNumber = await this.generateGlTransactionNumber('REV');

    // Create reversal transaction
    const [reversalTx] = await this.db
      .insert(glTransactions)
      .values({
        transactionNumber,
        subsidiaryId: originalTx.subsidiaryId,
        transactionDate: new Date().toISOString().split('T')[0],
        postingDate: new Date().toISOString().split('T')[0],
        periodId: originalTx.periodId,
        transactionType: 'REVERSAL',
        sourceSystem: 'INVENTORY',
        sourceTransactionId: originalTx.sourceTransactionId,
        sourceTransactionType: `${originalTx.sourceTransactionType}_REVERSAL`,
        description: `Reversal of ${originalTx.transactionNumber}: ${reversalReason}`,
        referenceNumber: originalTx.transactionNumber,
        baseCurrencyCode: originalTx.baseCurrencyCode,
        totalDebitAmount: originalTx.totalCreditAmount, // Swap
        totalCreditAmount: originalTx.totalDebitAmount, // Swap
        status: 'POSTED',
        autoGenerated: true,
        createdBy: this.context.userId,
        postedBy: this.context.userId,
        postedDate: new Date(),
      } as InsertGlTransaction)
      .returning();

    // Create reversed lines
    let lineNumber = 1;
    let totalDebits = 0;
    let totalCredits = 0;

    for (const line of originalLines) {
      const debitAmount = Number(line.creditAmount || 0); // Swap
      const creditAmount = Number(line.debitAmount || 0); // Swap

      await this.createGlLine(
        reversalTx.id,
        lineNumber++,
        line.accountId,
        line.subsidiaryId,
        debitAmount,
        creditAmount,
        `Reversal: ${line.description ?? ''}`
      );

      totalDebits += debitAmount;
      totalCredits += creditAmount;
    }

    // Mark original as reversed
    await this.db
      .update(glTransactions)
      .set({
        status: 'REVERSED',
        reversedByTransactionId: reversalTx.id,
        reversalReason,
        modifiedDate: new Date(),
      })
      .where(eq(glTransactions.id, glTransactionId));

    return {
      glTransactionId: reversalTx.id,
      transactionNumber,
      totalDebits,
      totalCredits,
      lineCount: lineNumber - 1,
    };
  }

  /**
   * Create a GL transaction line
   */
  private async createGlLine(
    transactionId: string,
    lineNumber: number,
    accountId: string,
    subsidiaryId: string,
    debitAmount: number,
    creditAmount: number,
    description: string
  ): Promise<void> {
    const currencyCode = this.context.baseCurrencyCode ?? 'USD';
    const exchangeRate = 1; // Same currency

    await this.db.insert(glTransactionLines).values({
      transactionId,
      lineNumber,
      accountId,
      subsidiaryId,
      debitAmount: String(debitAmount),
      creditAmount: String(creditAmount),
      currencyCode,
      exchangeRate: String(exchangeRate),
      baseDebitAmount: String(debitAmount * exchangeRate),
      baseCreditAmount: String(creditAmount * exchangeRate),
      description,
    } as InsertGlTransactionLine);
  }

  /**
   * Get accounting period for a date
   */
  private async getAccountingPeriod(subsidiaryId: string, dateStr: string): Promise<string> {
    const [period] = await this.db
      .select()
      .from(accountingPeriods)
      .where(
        and(
          eq(accountingPeriods.subsidiaryId, subsidiaryId),
          sql`${accountingPeriods.startDate} <= ${dateStr}`,
          sql`${accountingPeriods.endDate} >= ${dateStr}`,
          eq(accountingPeriods.status, 'OPEN')
        )
      );

    if (!period) {
      throw new Error(`No open accounting period found for date ${dateStr}`);
    }

    return period.id;
  }

  /**
   * Generate GL transaction number
   */
  private async generateGlTransactionNumber(prefix: string): Promise<string> {
    const year = new Date().getFullYear();
    const timestamp = Date.now().toString().slice(-8);
    return `GL-${prefix}-${year}-${timestamp}`;
  }
}
