# coding: utf-8

"""
    GLAPI - General Ledger and Accounting API

    # GLAPI - Comprehensive Accounting and Revenue Recognition API  GLAPI provides a complete accounting dimensions API with advanced revenue recognition capabilities.  ## Features  - **Multi-tenant Architecture**: Organization-based data isolation - **Accounting Dimensions**: Customers, Vendors, Subsidiaries, Departments, Locations, Classes - **Revenue Recognition**: ASC 606 compliant revenue recognition - **Inventory Management**: Items, Warehouses, Price Lists - **Financial Operations**: Invoices, Payments, Subscriptions - **General Ledger**: Chart of Accounts, GL Transactions  ## Authentication  All endpoints require authentication using Clerk. Include your authentication token in the Authorization header:  ``` Authorization: Bearer YOUR_TOKEN ```  ## Base URL  The API is accessible at: - Development: http://localhost:3031/api - Production: https://api.glapi.io/api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from glapi.api.price_lists_api import PriceListsApi


class TestPriceListsApi(unittest.TestCase):
    """PriceListsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PriceListsApi()

    def tearDown(self) -> None:
        pass

    def test_price_lists_create(self) -> None:
        """Test case for price_lists_create

        Create a new priceLists
        """
        pass

    def test_price_lists_delete(self) -> None:
        """Test case for price_lists_delete

        Delete a priceLists
        """
        pass

    def test_price_lists_get(self) -> None:
        """Test case for price_lists_get

        Get a specific priceLists by ID
        """
        pass

    def test_price_lists_list(self) -> None:
        """Test case for price_lists_list

        List all priceLists
        """
        pass

    def test_price_lists_update(self) -> None:
        """Test case for price_lists_update

        Update an existing priceLists
        """
        pass


if __name__ == '__main__':
    unittest.main()
