# coding: utf-8

"""
    GLAPI - General Ledger and Accounting API

    # GLAPI - Comprehensive Accounting and Revenue Recognition API  GLAPI provides a complete accounting dimensions API with advanced revenue recognition capabilities.  ## Features  - **Multi-tenant Architecture**: Organization-based data isolation - **Accounting Dimensions**: Customers, Vendors, Subsidiaries, Departments, Locations, Classes - **Revenue Recognition**: ASC 606 compliant revenue recognition - **Inventory Management**: Items, Warehouses, Price Lists - **Financial Operations**: Invoices, Payments, Subscriptions - **General Ledger**: Chart of Accounts, GL Transactions  ## Authentication  All endpoints require authentication using Clerk. Include your authentication token in the Authorization header:  ``` Authorization: Bearer YOUR_TOKEN ```  ## Base URL  The API is accessible at: - Development: http://localhost:3031/api - Production: https://api.glapi.io/api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from glapi.api.departments_api import DepartmentsApi


class TestDepartmentsApi(unittest.TestCase):
    """DepartmentsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DepartmentsApi()

    def tearDown(self) -> None:
        pass

    def test_departments_create(self) -> None:
        """Test case for departments_create

        Create a new departments
        """
        pass

    def test_departments_delete(self) -> None:
        """Test case for departments_delete

        Delete a departments
        """
        pass

    def test_departments_get(self) -> None:
        """Test case for departments_get

        Get a specific departments by ID
        """
        pass

    def test_departments_list(self) -> None:
        """Test case for departments_list

        List all departments
        """
        pass

    def test_departments_update(self) -> None:
        """Test case for departments_update

        Update an existing departments
        """
        pass


if __name__ == '__main__':
    unittest.main()
