# coding: utf-8

"""
    GLAPI - General Ledger and Accounting API

    # GLAPI - Comprehensive Accounting and Revenue Recognition API  GLAPI provides a complete accounting dimensions API with advanced revenue recognition capabilities.  ## Features  - **Multi-tenant Architecture**: Organization-based data isolation - **Accounting Dimensions**: Customers, Vendors, Subsidiaries, Departments, Locations, Classes - **Revenue Recognition**: ASC 606 compliant revenue recognition - **Inventory Management**: Items, Warehouses, Price Lists - **Financial Operations**: Invoices, Payments, Subscriptions - **General Ledger**: Chart of Accounts, GL Transactions  ## Authentication  All endpoints require authentication using Clerk. Include your authentication token in the Authorization header:  ``` Authorization: Bearer YOUR_TOKEN ```  ## Base URL  The API is accessible at: - Development: http://localhost:3031/api - Production: https://api.glapi.io/api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from glapi.api.vendors_api import VendorsApi


class TestVendorsApi(unittest.TestCase):
    """VendorsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = VendorsApi()

    def tearDown(self) -> None:
        pass

    def test_vendors_create(self) -> None:
        """Test case for vendors_create

        Create a new vendors
        """
        pass

    def test_vendors_delete(self) -> None:
        """Test case for vendors_delete

        Delete a vendors
        """
        pass

    def test_vendors_get(self) -> None:
        """Test case for vendors_get

        Get a specific vendors by ID
        """
        pass

    def test_vendors_list(self) -> None:
        """Test case for vendors_list

        List all vendors
        """
        pass

    def test_vendors_update(self) -> None:
        """Test case for vendors_update

        Update an existing vendors
        """
        pass


if __name__ == '__main__':
    unittest.main()
