# coding: utf-8

"""
    GLAPI - General Ledger and Accounting API

    # GLAPI - Comprehensive Accounting and Revenue Recognition API  GLAPI provides a complete accounting dimensions API with advanced revenue recognition capabilities.  ## Features  - **Multi-tenant Architecture**: Organization-based data isolation - **Accounting Dimensions**: Customers, Vendors, Subsidiaries, Departments, Locations, Classes - **Revenue Recognition**: ASC 606 compliant revenue recognition - **Inventory Management**: Items, Warehouses, Price Lists - **Financial Operations**: Invoices, Payments, Subscriptions - **General Ledger**: Chart of Accounts, GL Transactions  ## Authentication  All endpoints require authentication using Clerk. Include your authentication token in the Authorization header:  ``` Authorization: Bearer YOUR_TOKEN ```  ## Base URL  The API is accessible at: - Development: http://localhost:3031/api - Production: https://api.glapi.io/api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from glapi.api.business_transactions_api import BusinessTransactionsApi


class TestBusinessTransactionsApi(unittest.TestCase):
    """BusinessTransactionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BusinessTransactionsApi()

    def tearDown(self) -> None:
        pass

    def test_business_transactions_create(self) -> None:
        """Test case for business_transactions_create

        Create a new businessTransactions
        """
        pass

    def test_business_transactions_delete(self) -> None:
        """Test case for business_transactions_delete

        Delete a businessTransactions
        """
        pass

    def test_business_transactions_get(self) -> None:
        """Test case for business_transactions_get

        Get a specific businessTransactions by ID
        """
        pass

    def test_business_transactions_list(self) -> None:
        """Test case for business_transactions_list

        List all businessTransactions
        """
        pass

    def test_business_transactions_update(self) -> None:
        """Test case for business_transactions_update

        Update an existing businessTransactions
        """
        pass


if __name__ == '__main__':
    unittest.main()
