# coding: utf-8

"""
    GLAPI - General Ledger and Accounting API

    # GLAPI - Comprehensive Accounting and Revenue Recognition API  GLAPI provides a complete accounting dimensions API with advanced revenue recognition capabilities.  ## Features  - **Multi-tenant Architecture**: Organization-based data isolation - **Accounting Dimensions**: Customers, Vendors, Subsidiaries, Departments, Locations, Classes - **Revenue Recognition**: ASC 606 compliant revenue recognition - **Inventory Management**: Items, Warehouses, Price Lists - **Financial Operations**: Invoices, Payments, Subscriptions - **General Ledger**: Chart of Accounts, GL Transactions  ## Authentication  All endpoints require authentication using Clerk. Include your authentication token in the Authorization header:  ``` Authorization: Bearer YOUR_TOKEN ```  ## Base URL  The API is accessible at: - Development: http://localhost:3031/api - Production: https://api.glapi.io/api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from glapi.api.employees_api import EmployeesApi


class TestEmployeesApi(unittest.TestCase):
    """EmployeesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EmployeesApi()

    def tearDown(self) -> None:
        pass

    def test_employees_create(self) -> None:
        """Test case for employees_create

        Create a new employees
        """
        pass

    def test_employees_delete(self) -> None:
        """Test case for employees_delete

        Delete a employees
        """
        pass

    def test_employees_get(self) -> None:
        """Test case for employees_get

        Get a specific employees by ID
        """
        pass

    def test_employees_list(self) -> None:
        """Test case for employees_list

        List all employees
        """
        pass

    def test_employees_update(self) -> None:
        """Test case for employees_update

        Update an existing employees
        """
        pass


if __name__ == '__main__':
    unittest.main()
