# coding: utf-8

"""
    GLAPI - General Ledger and Accounting API

    # GLAPI - Comprehensive Accounting and Revenue Recognition API  GLAPI provides a complete accounting dimensions API with advanced revenue recognition capabilities.  ## Features  - **Multi-tenant Architecture**: Organization-based data isolation - **Accounting Dimensions**: Customers, Vendors, Subsidiaries, Departments, Locations, Classes - **Revenue Recognition**: ASC 606 compliant revenue recognition - **Inventory Management**: Items, Warehouses, Price Lists - **Financial Operations**: Invoices, Payments, Subscriptions - **General Ledger**: Chart of Accounts, GL Transactions  ## Authentication  All endpoints require authentication using Clerk. Include your authentication token in the Authorization header:  ``` Authorization: Bearer YOUR_TOKEN ```  ## Base URL  The API is accessible at: - Development: http://localhost:3031/api - Production: https://api.glapi.io/api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from glapi.api.units_of_measure_api import UnitsOfMeasureApi


class TestUnitsOfMeasureApi(unittest.TestCase):
    """UnitsOfMeasureApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UnitsOfMeasureApi()

    def tearDown(self) -> None:
        pass

    def test_units_of_measure_create(self) -> None:
        """Test case for units_of_measure_create

        Create a new unitsOfMeasure
        """
        pass

    def test_units_of_measure_delete(self) -> None:
        """Test case for units_of_measure_delete

        Delete a unitsOfMeasure
        """
        pass

    def test_units_of_measure_get(self) -> None:
        """Test case for units_of_measure_get

        Get a specific unitsOfMeasure by ID
        """
        pass

    def test_units_of_measure_list(self) -> None:
        """Test case for units_of_measure_list

        List all unitsOfMeasure
        """
        pass

    def test_units_of_measure_update(self) -> None:
        """Test case for units_of_measure_update

        Update an existing unitsOfMeasure
        """
        pass


if __name__ == '__main__':
    unittest.main()
