# coding: utf-8

"""
    GLAPI - General Ledger and Accounting API

    # GLAPI - Comprehensive Accounting and Revenue Recognition API  GLAPI provides a complete accounting dimensions API with advanced revenue recognition capabilities.  ## Features  - **Multi-tenant Architecture**: Organization-based data isolation - **Accounting Dimensions**: Customers, Vendors, Subsidiaries, Departments, Locations, Classes - **Revenue Recognition**: ASC 606 compliant revenue recognition - **Inventory Management**: Items, Warehouses, Price Lists - **Financial Operations**: Invoices, Payments, Subscriptions - **General Ledger**: Chart of Accounts, GL Transactions  ## Authentication  All endpoints require authentication using Clerk. Include your authentication token in the Authorization header:  ``` Authorization: Bearer YOUR_TOKEN ```  ## Base URL  The API is accessible at: - Development: http://localhost:3031/api - Production: https://api.glapi.io/api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from glapi.api.subsidiaries_api import SubsidiariesApi


class TestSubsidiariesApi(unittest.TestCase):
    """SubsidiariesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SubsidiariesApi()

    def tearDown(self) -> None:
        pass

    def test_subsidiaries_create(self) -> None:
        """Test case for subsidiaries_create

        Create a new subsidiaries
        """
        pass

    def test_subsidiaries_delete(self) -> None:
        """Test case for subsidiaries_delete

        Delete a subsidiaries
        """
        pass

    def test_subsidiaries_get(self) -> None:
        """Test case for subsidiaries_get

        Get a specific subsidiaries by ID
        """
        pass

    def test_subsidiaries_list(self) -> None:
        """Test case for subsidiaries_list

        List all subsidiaries
        """
        pass

    def test_subsidiaries_update(self) -> None:
        """Test case for subsidiaries_update

        Update an existing subsidiaries
        """
        pass


if __name__ == '__main__':
    unittest.main()
