import { BaseRepository } from './base-repository';
import { z } from 'zod';
declare const EntityTypeSchema: any;
type EntityType = z.infer<typeof EntityTypeSchema>;
declare const NewEntitySchema: any;
type NewEntity = z.infer<typeof NewEntitySchema>;
export declare class EntityRepository extends BaseRepository {
    findById(id: string, organizationId: string): Promise<{
        id: string;
        organizationId: string;
        name: string;
        displayName: string | null;
        code: string | null;
        entityTypes: string[];
        email: string | null;
        phone: string | null;
        website: string | null;
        addressId: string | null;
        parentEntityId: string | null;
        primaryContactId: string | null;
        taxId: string | null;
        description: string | null;
        notes: string | null;
        customFields: unknown;
        metadata: unknown;
        status: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        address: unknown;
    }>;
    findByCode(code: string, organizationId: string): Promise<{
        id: string;
        organizationId: string;
        name: string;
        displayName: string | null;
        code: string | null;
        entityTypes: string[];
        email: string | null;
        phone: string | null;
        website: string | null;
        addressId: string | null;
        parentEntityId: string | null;
        primaryContactId: string | null;
        taxId: string | null;
        description: string | null;
        notes: string | null;
        customFields: unknown;
        metadata: unknown;
        status: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        address: unknown;
    }>;
    findByEmail(email: string, organizationId: string): Promise<{
        id: string;
        organizationId: string;
        name: string;
        displayName: string | null;
        code: string | null;
        entityTypes: string[];
        email: string | null;
        phone: string | null;
        website: string | null;
        addressId: string | null;
        parentEntityId: string | null;
        primaryContactId: string | null;
        taxId: string | null;
        description: string | null;
        notes: string | null;
        customFields: unknown;
        metadata: unknown;
        status: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
    }>;
    findByTypes(types: EntityType[], organizationId: string, options?: {
        parentEntityId?: string | null;
        status?: string;
        isActive?: boolean;
        searchTerm?: string;
        limit?: number;
        offset?: number;
        orderBy?: 'name' | 'createdAt' | 'updatedAt';
        orderDirection?: 'asc' | 'desc';
    }): Promise<{
        id: string;
        organizationId: string;
        name: string;
        displayName: string | null;
        code: string | null;
        entityTypes: string[];
        email: string | null;
        phone: string | null;
        website: string | null;
        addressId: string | null;
        parentEntityId: string | null;
        primaryContactId: string | null;
        taxId: string | null;
        description: string | null;
        notes: string | null;
        customFields: unknown;
        metadata: unknown;
        status: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        address: unknown;
    }[]>;
    findContactsForEntity(entityId: string, organizationId: string): Promise<{
        id: string;
        organizationId: string;
        name: string;
        displayName: string | null;
        code: string | null;
        entityTypes: string[];
        email: string | null;
        phone: string | null;
        website: string | null;
        addressId: string | null;
        parentEntityId: string | null;
        primaryContactId: string | null;
        taxId: string | null;
        description: string | null;
        notes: string | null;
        customFields: unknown;
        metadata: unknown;
        status: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        address: unknown;
    }[]>;
    create(data: NewEntity): Promise<{
        id: string;
        name: string;
        organizationId: string;
        displayName: string | null;
        code: string | null;
        entityTypes: string[];
        email: string | null;
        phone: string | null;
        website: string | null;
        createdAt: Date;
        updatedAt: Date;
        addressId: string | null;
        parentEntityId: string | null;
        primaryContactId: string | null;
        taxId: string | null;
        description: string | null;
        notes: string | null;
        customFields: unknown;
        metadata: unknown;
        status: string;
        isActive: boolean;
    }>;
    update(id: string, organizationId: string, data: Partial<Omit<NewEntity, 'organizationId'>>): Promise<{
        id: string;
        organizationId: string;
        name: string;
        displayName: string | null;
        code: string | null;
        entityTypes: string[];
        email: string | null;
        phone: string | null;
        website: string | null;
        addressId: string | null;
        parentEntityId: string | null;
        primaryContactId: string | null;
        taxId: string | null;
        description: string | null;
        notes: string | null;
        customFields: unknown;
        metadata: unknown;
        status: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        address: unknown;
    }>;
    delete(id: string, organizationId: string): Promise<{
        id: string;
        name: string;
        organizationId: string;
        displayName: string | null;
        code: string | null;
        entityTypes: string[];
        email: string | null;
        phone: string | null;
        website: string | null;
        createdAt: Date;
        updatedAt: Date;
        addressId: string | null;
        parentEntityId: string | null;
        primaryContactId: string | null;
        taxId: string | null;
        description: string | null;
        notes: string | null;
        customFields: unknown;
        metadata: unknown;
        status: string;
        isActive: boolean;
    }>;
    addEntityType(id: string, organizationId: string, type: EntityType): Promise<{
        id: string;
        organizationId: string;
        name: string;
        displayName: string | null;
        code: string | null;
        entityTypes: string[];
        email: string | null;
        phone: string | null;
        website: string | null;
        addressId: string | null;
        parentEntityId: string | null;
        primaryContactId: string | null;
        taxId: string | null;
        description: string | null;
        notes: string | null;
        customFields: unknown;
        metadata: unknown;
        status: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        address: unknown;
    }>;
    removeEntityType(id: string, organizationId: string, type: EntityType): Promise<{
        id: string;
        organizationId: string;
        name: string;
        displayName: string | null;
        code: string | null;
        entityTypes: string[];
        email: string | null;
        phone: string | null;
        website: string | null;
        addressId: string | null;
        parentEntityId: string | null;
        primaryContactId: string | null;
        taxId: string | null;
        description: string | null;
        notes: string | null;
        customFields: unknown;
        metadata: unknown;
        status: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        address: unknown;
    }>;
    countByTypes(types: EntityType[], organizationId: string, filters?: {
        parentEntityId?: string | null;
        status?: string;
        isActive?: boolean;
        searchTerm?: string;
    }): Promise<{}>;
}
export {};
//# sourceMappingURL=entity-repository.d.ts.map