import { BaseRepository } from './base-repository';
export interface GlTransactionPaginationParams {
    page?: number;
    limit?: number;
    orderBy?: 'transactionNumber' | 'transactionDate' | 'postingDate';
    orderDirection?: 'asc' | 'desc';
}
export interface GlTransactionFilters {
    subsidiaryId?: string;
    periodId?: string;
    status?: string;
    transactionType?: string;
    dateFrom?: string | Date;
    dateTo?: string | Date;
    sourceTransactionId?: string;
}
export interface AccountActivityFilters {
    accountId: string;
    subsidiaryId?: string;
    dateFrom: string | Date;
    dateTo: string | Date;
    classId?: string;
    departmentId?: string;
    locationId?: string;
}
export interface TrialBalanceFilters {
    periodId: string;
    subsidiaryId?: string;
    includeInactive?: boolean;
    classId?: string;
    departmentId?: string;
    locationId?: string;
}
export declare class GlReportingRepository extends BaseRepository {
    /**
     * Get subsidiaries accessible to an organization
     */
    private getOrganizationSubsidiaries;
    /**
     * Validate that a subsidiary belongs to the organization
     */
    private validateSubsidiaryAccess;
    /**
     * Find GL transaction by ID with organization RLS
     */
    findGlTransactionById(id: string, organizationId: string): Promise<{
        id: string;
        transactionNumber: string;
        subsidiaryId: string;
        transactionDate: string;
        postingDate: string;
        periodId: string;
        transactionType: string;
        sourceSystem: string | null;
        sourceTransactionId: string | null;
        sourceTransactionType: string | null;
        description: string | null;
        referenceNumber: string | null;
        baseCurrencyCode: string;
        totalDebitAmount: string;
        totalCreditAmount: string;
        status: string;
        recurringTemplateId: string | null;
        reversedByTransactionId: string | null;
        reversalReason: string | null;
        autoGenerated: boolean;
        createdBy: string | null;
        createdDate: Date;
        modifiedBy: string | null;
        modifiedDate: Date;
        postedBy: string | null;
        postedDate: Date | null;
        versionNumber: number;
    } | null>;
    /**
     * List GL transactions with organization RLS
     */
    findAllGlTransactions(organizationId: string, params?: GlTransactionPaginationParams, filters?: GlTransactionFilters): Promise<{
        data: {
            id: string;
            transactionNumber: string;
            subsidiaryId: string;
            transactionDate: string;
            postingDate: string;
            periodId: string;
            transactionType: string;
            sourceSystem: string | null;
            sourceTransactionId: string | null;
            sourceTransactionType: string | null;
            description: string | null;
            referenceNumber: string | null;
            baseCurrencyCode: string;
            totalDebitAmount: string;
            totalCreditAmount: string;
            status: string;
            recurringTemplateId: string | null;
            reversedByTransactionId: string | null;
            reversalReason: string | null;
            autoGenerated: boolean;
            createdBy: string | null;
            createdDate: Date;
            modifiedBy: string | null;
            modifiedDate: Date;
            postedBy: string | null;
            postedDate: Date | null;
            versionNumber: number;
        }[];
        total: number;
        page: number;
        limit: number;
        totalPages: number;
    }>;
    /**
     * Get GL transaction lines with organization RLS
     */
    getGlTransactionLines(transactionId: string, organizationId: string): Promise<{
        id: string;
        transactionId: string;
        lineNumber: number;
        accountId: string;
        classId: string | null;
        departmentId: string | null;
        locationId: string | null;
        subsidiaryId: string;
        debitAmount: string;
        creditAmount: string;
        currencyCode: string;
        exchangeRate: string;
        baseDebitAmount: string;
        baseCreditAmount: string;
        description: string | null;
        reference1: string | null;
        reference2: string | null;
        projectId: string | null;
        createdDate: Date;
    }[]>;
    /**
     * Get account activity with organization RLS
     */
    getAccountActivity(filters: AccountActivityFilters, organizationId: string, params?: {
        page?: number;
        limit?: number;
    }): Promise<{
        data: {
            debitAmount: number;
            creditAmount: number;
            runningBalance: number;
            date: string;
            transactionNumber: string;
            description: string | null;
            reference: string | null;
            glTransactionId: string;
            sourceTransactionId: string | null;
        }[];
        total: number;
        page: number;
        limit: number;
        totalPages: number;
    }>;
    /**
     * Get trial balance with organization RLS
     */
    getTrialBalance(filters: TrialBalanceFilters, organizationId: string): Promise<{
        periodName: string;
        subsidiaryName: string;
        asOfDate: string;
        entries: {
            accountId: string;
            accountNumber: string;
            accountName: string;
            accountType: "Asset" | "Liability" | "Equity" | "Revenue" | "COGS" | "Expense";
            debitBalance: number;
            creditBalance: number;
            netBalance: number;
            periodActivity: {
                debits: number;
                credits: number;
                net: number;
            };
            ytdActivity: {
                debits: number;
                credits: number;
                net: number;
            };
        }[];
        totals: {
            totalDebits: number;
            totalCredits: number;
            difference: number;
        };
    }>;
    /**
     * Get general ledger entries with organization RLS
     */
    getGeneralLedger(filters: {
        subsidiaryId?: string;
        periodId?: string;
        dateFrom?: string | Date;
        dateTo?: string | Date;
        accountIds?: string[];
        includeAdjustments?: boolean;
        groupBy?: 'account' | 'date' | 'transaction';
    }, organizationId: string, params?: {
        page?: number;
        limit?: number;
    }): Promise<{
        data: {
            debitAmount: number;
            creditAmount: number;
            glTransactionId: string;
            transactionNumber: string;
            transactionDate: string;
            postingDate: string;
            description: string | null;
            accountId: string;
            accountNumber: string;
            accountName: string;
            reference1: string | null;
            reference2: string | null;
            classId: string | null;
            departmentId: string | null;
            locationId: string | null;
        }[];
        total: number;
        page: number;
        limit: number;
        totalPages: number;
    }>;
}
//# sourceMappingURL=gl-reporting-repository.d.ts.map