export * from './base-repository';
export * from './customer-repository';
export * from './organization-repository';
export * from './subsidiary-repository';
export * from './department-repository';
export * from './location-repository';
export * from './class-repository';
export * from './account-repository';
export * from './entity-repository';
export * from './gl-transaction-repository';
export * from './gl-reporting-repository';
import { DepartmentRepository } from './department-repository';
import { LocationRepository } from './location-repository';
import { ClassRepository } from './class-repository';
import { AccountRepository } from './account-repository';
import { EntityRepository } from './entity-repository';
import { GlTransactionRepository } from './gl-transaction-repository';
import { GlReportingRepository } from './gl-reporting-repository';
export declare const departmentRepository: DepartmentRepository;
export declare const locationRepository: LocationRepository;
export declare const classRepository: ClassRepository;
export declare const accountRepository: AccountRepository;
export declare const entityRepository: EntityRepository;
export declare const glTransactionRepository: GlTransactionRepository;
export declare const glReportingRepository: GlReportingRepository;
//# sourceMappingURL=index.d.ts.map