#!/usr/bin/env tsx
/**
 * AI Tool Generator
 *
 * Generates AI tool definitions from OpenAPI specification with x-ai-* extensions.
 *
 * Generates:
 * - generated-tools.ts: Function declarations and metadata for LLMs
 * - generated-executor.ts: tRPC-based tool executor with validation
 * - tools-manifest.json: Manifest with content hash for cache invalidation
 *
 * Usage:
 *   pnpm --filter @glapi/trpc generate-ai-tools
 *
 * @see docs/architecture/ai-openapi.md
 */

import { writeFileSync, mkdirSync, readFileSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { createHash } from 'crypto';
import { generateOpenAPISpec, type OpenAPISpec } from '../src/openapi-generator';

// =============================================================================
// Configuration
// =============================================================================

const OUTPUT_DIR = join(__dirname, '../../../apps/web/src/lib/ai/generated');
const MANIFEST_FILE = join(OUTPUT_DIR, 'tools-manifest.json');
const TOOLS_FILE = join(OUTPUT_DIR, 'generated-tools.ts');
const EXECUTOR_FILE = join(OUTPUT_DIR, 'generated-executor.ts');
const INDEX_FILE = join(OUTPUT_DIR, 'index.ts');

// =============================================================================
// Types
// =============================================================================

interface AIToolExtension {
  name: string;
  version?: number;
  stability?: string;
  deprecated?: boolean;
  description: string;
  scopes?: string[];
  enabled?: boolean;
  exampleUtterances?: string[];
}

interface AIRiskExtension {
  level: string;
  requiresConfirmation?: boolean;
  supportsDryRun?: boolean;
  confirmationMessage?: string;
}

interface AIPermissionsExtension {
  required: string[];
  minimumRole: string;
}

interface AIRateLimitExtension {
  requestsPerMinute: number;
  burstLimit?: number;
  scope?: string;
}

interface AICacheExtension {
  enabled?: boolean;
  ttlSeconds?: number;
  varyBy?: string[];
}

interface AIOutputExtension {
  includeFields?: string[];
  redactFields?: string[];
  maxItems?: number;
  maxTokens?: number;
}

interface ExtractedTool {
  operationId: string;
  path: string;
  method: string;
  summary: string;
  tool: AIToolExtension;
  risk: AIRiskExtension;
  permissions: AIPermissionsExtension;
  rateLimit?: AIRateLimitExtension;
  cache?: AICacheExtension;
  output?: AIOutputExtension;
  parameters: any[];
  requestBody?: any;
}

// =============================================================================
// Tool Extraction
// =============================================================================

function extractToolsFromSpec(spec: OpenAPISpec): ExtractedTool[] {
  const tools: ExtractedTool[] = [];

  for (const [path, pathItem] of Object.entries(spec.paths)) {
    for (const [method, operation] of Object.entries(pathItem as Record<string, any>)) {
      // Skip if no AI extensions
      if (!operation['x-ai-tool']) continue;

      const tool: ExtractedTool = {
        operationId: operation.operationId,
        path,
        method: method.toUpperCase(),
        summary: operation.summary || '',
        tool: operation['x-ai-tool'],
        risk: operation['x-ai-risk'] || { level: 'LOW' },
        permissions: operation['x-ai-permissions'] || { required: [], minimumRole: 'viewer' },
        rateLimit: operation['x-ai-rate-limit'],
        cache: operation['x-ai-cache'],
        output: operation['x-ai-output'],
        parameters: operation.parameters || [],
        requestBody: operation.requestBody,
      };

      tools.push(tool);
    }
  }

  return tools;
}

// =============================================================================
// Code Generation
// =============================================================================

function generateToolsFile(tools: ExtractedTool[]): string {
  const toolDefinitions = tools
    .filter((t) => t.tool.enabled !== false)
    .map((t) => generateToolDefinition(t))
    .join('\n\n');

  return `/**
 * Generated AI Tool Definitions
 *
 * DO NOT EDIT - This file is auto-generated by generate-ai-tools.ts
 * @generated
 */

import type { ChatCompletionTool } from 'openai/resources/chat/completions';

// =============================================================================
// Types
// =============================================================================

export type RiskLevel = 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
export type UserRole = 'viewer' | 'staff' | 'manager' | 'accountant' | 'admin';

export interface AIToolMetadata {
  name: string;
  version: number;
  stability: 'stable' | 'beta' | 'experimental';
  deprecated: boolean;
  description: string;
  scopes: string[];
  enabled: boolean;
  exampleUtterances?: string[];
  risk: {
    level: RiskLevel;
    requiresConfirmation: boolean;
    supportsDryRun: boolean;
    confirmationMessage?: string;
  };
  permissions: {
    required: string[];
    minimumRole: UserRole;
  };
  rateLimit?: {
    requestsPerMinute: number;
    burstLimit?: number;
    scope: 'user' | 'organization' | 'global';
  };
  cache?: {
    enabled: boolean;
    ttlSeconds: number;
    varyBy?: string[];
  };
  output?: {
    includeFields?: string[];
    redactFields?: string[];
    maxItems?: number;
    maxTokens?: number;
  };
  operationId: string;
  path: string;
  method: string;
}

export interface GeneratedAITool {
  functionDeclaration: ChatCompletionTool;
  metadata: AIToolMetadata;
}

// =============================================================================
// Tool Definitions
// =============================================================================

${toolDefinitions}

// =============================================================================
// Tool Registry
// =============================================================================

export const AI_TOOLS: GeneratedAITool[] = [
${tools
  .filter((t) => t.tool.enabled !== false)
  .map((t) => `  ${t.tool.name.toUpperCase()}_TOOL,`)
  .join('\n')}
];

export const AI_TOOLS_BY_NAME = new Map<string, GeneratedAITool>(
  AI_TOOLS.map((tool) => [tool.metadata.name, tool])
);

export const AI_TOOLS_BY_SCOPE = new Map<string, GeneratedAITool[]>();
for (const tool of AI_TOOLS) {
  for (const scope of tool.metadata.scopes) {
    const existing = AI_TOOLS_BY_SCOPE.get(scope) || [];
    existing.push(tool);
    AI_TOOLS_BY_SCOPE.set(scope, existing);
  }
}

/**
 * Get tools filtered by scope(s)
 */
export function getToolsByScope(scopes: string[]): GeneratedAITool[] {
  const result = new Set<GeneratedAITool>();
  for (const scope of scopes) {
    const tools = AI_TOOLS_BY_SCOPE.get(scope) || [];
    for (const tool of tools) {
      result.add(tool);
    }
  }
  return Array.from(result);
}

/**
 * Get tool by name
 */
export function getToolByName(name: string): GeneratedAITool | undefined {
  return AI_TOOLS_BY_NAME.get(name);
}

/**
 * Get OpenAI-compatible tool definitions for a set of scopes
 */
export function getOpenAITools(scopes: string[]): ChatCompletionTool[] {
  return getToolsByScope(scopes).map((t) => t.functionDeclaration);
}

/**
 * Total number of generated tools
 */
export const TOOL_COUNT = ${tools.filter((t) => t.tool.enabled !== false).length};
`;
}

function generateToolDefinition(tool: ExtractedTool): string {
  const constName = `${tool.tool.name.toUpperCase()}_TOOL`;

  // Build parameter schema
  const paramSchema = buildParameterSchema(tool);

  return `export const ${constName}: GeneratedAITool = {
  functionDeclaration: {
    type: 'function',
    function: {
      name: '${tool.tool.name}',
      description: ${JSON.stringify(tool.tool.description)},
      parameters: ${JSON.stringify(paramSchema, null, 6).replace(/\n/g, '\n      ')},
    },
  },
  metadata: {
    name: '${tool.tool.name}',
    version: ${tool.tool.version ?? 1},
    stability: '${tool.tool.stability ?? 'stable'}',
    deprecated: ${tool.tool.deprecated ?? false},
    description: ${JSON.stringify(tool.tool.description)},
    scopes: ${JSON.stringify(tool.tool.scopes ?? ['global'])},
    enabled: ${tool.tool.enabled ?? true},${
      tool.tool.exampleUtterances
        ? `\n    exampleUtterances: ${JSON.stringify(tool.tool.exampleUtterances)},`
        : ''
    }
    risk: {
      level: '${tool.risk.level}',
      requiresConfirmation: ${tool.risk.requiresConfirmation ?? false},
      supportsDryRun: ${tool.risk.supportsDryRun ?? false},${
        tool.risk.confirmationMessage
          ? `\n      confirmationMessage: ${JSON.stringify(tool.risk.confirmationMessage)},`
          : ''
      }
    },
    permissions: {
      required: ${JSON.stringify(tool.permissions.required)},
      minimumRole: '${tool.permissions.minimumRole}',
    },${
      tool.rateLimit
        ? `\n    rateLimit: {
      requestsPerMinute: ${tool.rateLimit.requestsPerMinute},${tool.rateLimit.burstLimit ? `\n      burstLimit: ${tool.rateLimit.burstLimit},` : ''}
      scope: '${tool.rateLimit.scope ?? 'user'}',
    },`
        : ''
    }${
      tool.cache
        ? `\n    cache: {
      enabled: ${tool.cache.enabled ?? false},
      ttlSeconds: ${tool.cache.ttlSeconds ?? 300},${tool.cache.varyBy ? `\n      varyBy: ${JSON.stringify(tool.cache.varyBy)},` : ''}
    },`
        : ''
    }${
      tool.output
        ? `\n    output: {${tool.output.includeFields ? `\n      includeFields: ${JSON.stringify(tool.output.includeFields)},` : ''}${tool.output.redactFields ? `\n      redactFields: ${JSON.stringify(tool.output.redactFields)},` : ''}${tool.output.maxItems ? `\n      maxItems: ${tool.output.maxItems},` : ''}${tool.output.maxTokens ? `\n      maxTokens: ${tool.output.maxTokens},` : ''}
    },`
        : ''
    }
    operationId: '${tool.operationId}',
    path: '${tool.path}',
    method: '${tool.method}',
  },
};`;
}

function buildParameterSchema(tool: ExtractedTool): any {
  const schema: any = {
    type: 'object',
    properties: {},
    required: [],
  };

  // Add path/query parameters
  for (const param of tool.parameters) {
    const propName = param.name;
    schema.properties[propName] = param.schema || { type: 'string' };
    if (param.description) {
      schema.properties[propName].description = param.description;
    }
    if (param.required) {
      schema.required.push(propName);
    }
  }

  // Add request body properties (for mutations)
  if (tool.requestBody?.content?.['application/json']?.schema) {
    const bodySchema = tool.requestBody.content['application/json'].schema;
    if (bodySchema.properties) {
      for (const [key, value] of Object.entries(bodySchema.properties)) {
        schema.properties[key] = value;
      }
      if (bodySchema.required) {
        schema.required.push(...bodySchema.required);
      }
    }
  }

  if (schema.required.length === 0) {
    delete schema.required;
  }

  return schema;
}

function generateExecutorFile(tools: ExtractedTool[]): string {
  const toolCases = tools
    .filter((t) => t.tool.enabled !== false)
    .map((t) => generateToolCase(t))
    .join('\n\n');

  return `/**
 * Generated AI Tool Executor
 *
 * DO NOT EDIT - This file is auto-generated by generate-ai-tools.ts
 * @generated
 */

import { z } from 'zod';
import { TRPCError } from '@trpc/server';
import { AI_TOOLS_BY_NAME, type GeneratedAITool, type RiskLevel } from './generated-tools';
import { applyOutputShaping, type OutputConfig } from '../output-shaping';

// =============================================================================
// Types
// =============================================================================

export interface ExecutionContext {
  userId: string;
  organizationId: string;
  userRole: string;
  authToken: string;
  dryRun?: boolean;
  idempotencyKey?: string;
}

export interface ExecutionResult<T = unknown> {
  success: boolean;
  data?: T;
  error?: {
    code: string;
    message: string;
    retryable: boolean;
    details?: unknown;
  };
  preview?: boolean;
  fromCache?: boolean;
  executionTimeMs?: number;
  outputShaping?: {
    applied: boolean;
    fieldsRedacted: number;
    itemsLimited: number;
    tokensTruncated: boolean;
  };
}

export interface ToolExecutorConfig {
  trpcCaller: any; // tRPC caller instance
  cache?: {
    get: (key: string) => Promise<unknown | null>;
    set: (key: string, value: unknown, ttlSeconds: number) => Promise<void>;
  };
  rateLimiter?: {
    check: (toolName: string, context: ExecutionContext) => Promise<{ allowed: boolean; retryAfterMs?: number }>;
  };
}

// =============================================================================
// Validation Schemas
// =============================================================================

${tools
  .filter((t) => t.tool.enabled !== false)
  .map((t) => generateValidationSchema(t))
  .join('\n\n')}

const VALIDATION_SCHEMAS: Record<string, z.ZodType<any>> = {
${tools
  .filter((t) => t.tool.enabled !== false)
  .map((t) => `  '${t.tool.name}': ${t.tool.name.replace(/_/g, '')}Schema,`)
  .join('\n')}
};

// =============================================================================
// Permission Checking
// =============================================================================

const ROLE_HIERARCHY: Record<string, number> = {
  viewer: 0,
  staff: 1,
  manager: 2,
  accountant: 3,
  admin: 4,
};

function hasMinimumRole(userRole: string, minimumRole: string): boolean {
  return (ROLE_HIERARCHY[userRole] ?? 0) >= (ROLE_HIERARCHY[minimumRole] ?? 0);
}

function checkPermissions(
  tool: GeneratedAITool,
  context: ExecutionContext
): { allowed: boolean; reason?: string } {
  // Check minimum role
  if (!hasMinimumRole(context.userRole, tool.metadata.permissions.minimumRole)) {
    return {
      allowed: false,
      reason: \`Requires minimum role: \${tool.metadata.permissions.minimumRole}\`,
    };
  }

  // TODO: Check specific permissions against user's permission set
  // For now, role check is sufficient

  return { allowed: true };
}

// =============================================================================
// Tool Executor Factory
// =============================================================================

export function createToolExecutor(config: ToolExecutorConfig) {
  const { trpcCaller, cache, rateLimiter } = config;

  /**
   * Execute a tool by name with parameters
   */
  async function executeTool(
    toolName: string,
    parameters: unknown,
    context: ExecutionContext
  ): Promise<ExecutionResult> {
    const startTime = Date.now();

    // Get tool definition
    const tool = AI_TOOLS_BY_NAME.get(toolName);
    if (!tool) {
      return {
        success: false,
        error: {
          code: 'TOOL_NOT_FOUND',
          message: \`Unknown tool: \${toolName}\`,
          retryable: false,
        },
      };
    }

    // Check if tool is enabled
    if (!tool.metadata.enabled) {
      return {
        success: false,
        error: {
          code: 'TOOL_DISABLED',
          message: \`Tool is disabled: \${toolName}\`,
          retryable: false,
        },
      };
    }

    // Check permissions
    const permCheck = checkPermissions(tool, context);
    if (!permCheck.allowed) {
      return {
        success: false,
        error: {
          code: 'PERMISSION_DENIED',
          message: permCheck.reason || 'Permission denied',
          retryable: false,
        },
      };
    }

    // Check rate limit
    if (rateLimiter) {
      const limitCheck = await rateLimiter.check(toolName, context);
      if (!limitCheck.allowed) {
        return {
          success: false,
          error: {
            code: 'RATE_LIMITED',
            message: 'Rate limit exceeded. Please try again later.',
            retryable: true,
            details: { retryAfterMs: limitCheck.retryAfterMs },
          },
        };
      }
    }

    // Validate parameters
    const schema = VALIDATION_SCHEMAS[toolName];
    if (schema) {
      const parseResult = schema.safeParse(parameters);
      if (!parseResult.success) {
        return {
          success: false,
          error: {
            code: 'VALIDATION_ERROR',
            message: 'Parameter validation failed',
            retryable: false,
            details: parseResult.error.flatten(),
          },
        };
      }
      parameters = parseResult.data;
    }

    // Check cache for read operations
    // Note: Cached data is already output-shaped (we store shaped results)
    if (cache && tool.metadata.cache?.enabled && tool.metadata.method === 'GET') {
      const cacheKey = buildCacheKey(toolName, parameters, context);
      const cached = await cache.get(cacheKey);
      if (cached !== null) {
        return {
          success: true,
          data: cached,
          fromCache: true,
          executionTimeMs: Date.now() - startTime,
          outputShaping: {
            applied: !!tool.metadata.output,
            fieldsRedacted: 0, // Already redacted when cached
            itemsLimited: 0,
            tokensTruncated: false,
          },
        };
      }
    }

    // Execute tool
    try {
      const rawResult = await executeToolImplementation(toolName, parameters, context, trpcCaller);

      // Apply output shaping BEFORE caching or returning
      // This ensures redacted data is never stored or logged
      const outputConfig = tool.metadata.output as OutputConfig | undefined;
      const { data: shapedResult, stats: shapingStats } = applyOutputShaping(rawResult, outputConfig);

      // Cache the SHAPED result (not raw) if enabled
      if (cache && tool.metadata.cache?.enabled && tool.metadata.method === 'GET') {
        const cacheKey = buildCacheKey(toolName, parameters, context);
        await cache.set(cacheKey, shapedResult, tool.metadata.cache.ttlSeconds);
      }

      return {
        success: true,
        data: shapedResult,
        preview: context.dryRun,
        executionTimeMs: Date.now() - startTime,
        outputShaping: {
          applied: !!outputConfig,
          fieldsRedacted: shapingStats.fieldsRedacted,
          itemsLimited: shapingStats.itemsLimited,
          tokensTruncated: shapingStats.tokensTruncated,
        },
      };
    } catch (error) {
      const trpcError = error as TRPCError;
      return {
        success: false,
        error: {
          code: trpcError.code || 'EXECUTION_ERROR',
          message: trpcError.message || 'Tool execution failed',
          retryable: isRetryableError(trpcError),
          details: trpcError.cause,
        },
        executionTimeMs: Date.now() - startTime,
      };
    }
  }

  return { executeTool };
}

function buildCacheKey(
  toolName: string,
  parameters: unknown,
  context: ExecutionContext
): string {
  const tool = AI_TOOLS_BY_NAME.get(toolName);
  const varyBy = tool?.metadata.cache?.varyBy || [];

  const keyParts = [
    \`ai:tool:\${toolName}\`,
    \`org:\${context.organizationId}\`,
  ];

  if (varyBy.length > 0 && typeof parameters === 'object' && parameters !== null) {
    for (const key of varyBy) {
      const value = (parameters as Record<string, unknown>)[key];
      if (value !== undefined) {
        keyParts.push(\`\${key}:\${JSON.stringify(value)}\`);
      }
    }
  } else {
    keyParts.push(\`params:\${JSON.stringify(parameters)}\`);
  }

  return keyParts.join(':');
}

function isRetryableError(error: TRPCError): boolean {
  const nonRetryableCodes = ['BAD_REQUEST', 'UNAUTHORIZED', 'FORBIDDEN', 'NOT_FOUND'];
  return !nonRetryableCodes.includes(error.code);
}

// =============================================================================
// Tool Implementations
// =============================================================================

async function executeToolImplementation(
  toolName: string,
  parameters: unknown,
  context: ExecutionContext,
  trpcCaller: any
): Promise<unknown> {
  const params = parameters as Record<string, unknown>;

  switch (toolName) {
${toolCases}

    default:
      throw new TRPCError({
        code: 'NOT_FOUND',
        message: \`No implementation for tool: \${toolName}\`,
      });
  }
}
`;
}

function generateValidationSchema(tool: ExtractedTool): string {
  const schemaName = `${tool.tool.name.replace(/_/g, '')}Schema`;
  const props: string[] = [];

  // Add path/query parameters
  for (const param of tool.parameters) {
    const zodType = getZodType(param.schema);
    const isOptional = !param.required;
    props.push(`  ${param.name}: ${zodType}${isOptional ? '.optional()' : ''}`);
  }

  // Add request body properties
  if (tool.requestBody?.content?.['application/json']?.schema?.properties) {
    const bodySchema = tool.requestBody.content['application/json'].schema;
    for (const [key, value] of Object.entries(bodySchema.properties as Record<string, any>)) {
      const zodType = getZodType(value);
      const isRequired = bodySchema.required?.includes(key);
      props.push(`  ${key}: ${zodType}${isRequired ? '' : '.optional()'}`);
    }
  }

  return `const ${schemaName} = z.object({
${props.join(',\n')}
});`;
}

function getZodType(schema: any): string {
  if (!schema) return 'z.unknown()';

  switch (schema.type) {
    case 'string':
      if (schema.format === 'uuid') return 'z.string().uuid()';
      if (schema.format === 'email') return 'z.string().email()';
      if (schema.enum) return `z.enum([${schema.enum.map((e: string) => `'${e}'`).join(', ')}])`;
      return 'z.string()';
    case 'number':
    case 'integer':
      return 'z.number()';
    case 'boolean':
      return 'z.boolean()';
    case 'array':
      return `z.array(${getZodType(schema.items)})`;
    case 'object':
      return 'z.record(z.unknown())';
    default:
      return 'z.unknown()';
  }
}

function generateToolCase(tool: ExtractedTool): string {
  // Parse the operationId to get router and method
  // e.g., "customers.list" -> router: "customers", method: "list"
  const [routerName, methodName] = tool.operationId.split('.');

  // Build the tRPC call based on the method
  if (tool.method === 'GET') {
    // For GET requests, call the query
    if (methodName === 'list') {
      return `    case '${tool.tool.name}': {
      const result = await trpcCaller.${routerName}.${methodName}(params);
      return { ${routerName}: result, count: Array.isArray(result) ? result.length : 1 };
    }`;
    } else {
      // get by id
      return `    case '${tool.tool.name}': {
      const result = await trpcCaller.${routerName}.${methodName}({ id: params.id as string });
      return result;
    }`;
    }
  } else if (tool.method === 'POST') {
    // For POST requests, call the mutation
    return `    case '${tool.tool.name}': {
      if (context.dryRun) {
        return { preview: true, wouldCreate: params };
      }
      const result = await trpcCaller.${routerName}.${methodName}(params);
      return result;
    }`;
  } else if (tool.method === 'PUT') {
    return `    case '${tool.tool.name}': {
      if (context.dryRun) {
        return { preview: true, wouldUpdate: { id: params.id, ...params } };
      }
      const result = await trpcCaller.${routerName}.${methodName}({ id: params.id as string, data: params });
      return result;
    }`;
  } else if (tool.method === 'DELETE') {
    return `    case '${tool.tool.name}': {
      if (context.dryRun) {
        return { preview: true, wouldDelete: params.id };
      }
      await trpcCaller.${routerName}.${methodName}({ id: params.id as string });
      return { deleted: true, id: params.id };
    }`;
  }

  return `    case '${tool.tool.name}': {
      throw new TRPCError({ code: 'NOT_IMPLEMENTED', message: 'Tool not yet implemented' });
    }`;
}

function generateIndexFile(): string {
  return `/**
 * Generated AI Tools - Public API
 *
 * DO NOT EDIT - This file is auto-generated by generate-ai-tools.ts
 * @generated
 */

export {
  // Tools
  AI_TOOLS,
  AI_TOOLS_BY_NAME,
  AI_TOOLS_BY_SCOPE,
  getToolsByScope,
  getToolByName,
  getOpenAITools,
  TOOL_COUNT,
  // Types
  type GeneratedAITool,
  type AIToolMetadata,
  type RiskLevel,
  type UserRole,
} from './generated-tools';

export {
  // Executor
  createToolExecutor,
  // Types
  type ExecutionContext,
  type ExecutionResult,
  type ToolExecutorConfig,
} from './generated-executor';

// Re-export manifest
export { default as toolsManifest } from './tools-manifest.json';
`;
}

function generateManifest(tools: ExtractedTool[], toolsContent: string): object {
  const hash = createHash('sha256').update(toolsContent).digest('hex').slice(0, 12);

  return {
    version: '1.0.0',
    generatedAt: new Date().toISOString(),
    contentHash: hash,
    toolCount: tools.filter((t) => t.tool.enabled !== false).length,
    tools: tools
      .filter((t) => t.tool.enabled !== false)
      .map((t) => ({
        name: t.tool.name,
        version: t.tool.version ?? 1,
        stability: t.tool.stability ?? 'stable',
        riskLevel: t.risk.level,
        scopes: t.tool.scopes ?? ['global'],
      })),
  };
}

// =============================================================================
// Main
// =============================================================================

console.log('🤖 Generating AI Tools from OpenAPI specification...\n');

try {
  // Ensure output directory exists
  mkdirSync(OUTPUT_DIR, { recursive: true });

  // Generate OpenAPI spec with AI extensions
  const spec = generateOpenAPISpec({ includeAIExtensions: true, useDefaultAIMeta: true });

  // Extract tools from spec
  const tools = extractToolsFromSpec(spec);
  console.log(`📊 Found ${tools.length} AI-enabled operations\n`);

  if (tools.length === 0) {
    console.log('⚠️  No AI-enabled operations found. Ensure x-ai-tool extensions are present.');
    process.exit(0);
  }

  // Generate files
  const toolsContent = generateToolsFile(tools);
  const executorContent = generateExecutorFile(tools);
  const indexContent = generateIndexFile();
  const manifest = generateManifest(tools, toolsContent);

  // Write files
  writeFileSync(TOOLS_FILE, toolsContent, 'utf-8');
  console.log(`✅ Generated: ${TOOLS_FILE}`);

  writeFileSync(EXECUTOR_FILE, executorContent, 'utf-8');
  console.log(`✅ Generated: ${EXECUTOR_FILE}`);

  writeFileSync(INDEX_FILE, indexContent, 'utf-8');
  console.log(`✅ Generated: ${INDEX_FILE}`);

  writeFileSync(MANIFEST_FILE, JSON.stringify(manifest, null, 2), 'utf-8');
  console.log(`✅ Generated: ${MANIFEST_FILE}`);

  // Summary
  console.log('\n📊 Generation Summary:');
  console.log(`   - Tools: ${tools.filter((t) => t.tool.enabled !== false).length}`);
  console.log(`   - Content Hash: ${(manifest as any).contentHash}`);

  const scopeCounts = new Map<string, number>();
  for (const tool of tools) {
    for (const scope of tool.tool.scopes ?? ['global']) {
      scopeCounts.set(scope, (scopeCounts.get(scope) ?? 0) + 1);
    }
  }
  console.log(`   - Scopes: ${Array.from(scopeCounts.entries()).map(([s, c]) => `${s}(${c})`).join(', ')}`);

  const riskCounts = new Map<string, number>();
  for (const tool of tools) {
    riskCounts.set(tool.risk.level, (riskCounts.get(tool.risk.level) ?? 0) + 1);
  }
  console.log(`   - Risk Levels: ${Array.from(riskCounts.entries()).map(([r, c]) => `${r}(${c})`).join(', ')}`);

  console.log('\n✨ Done!\n');
  console.log('💡 Next steps:');
  console.log('   1. Import generated tools: import { AI_TOOLS } from "@/lib/ai/generated"');
  console.log('   2. Use getToolsByScope() for dynamic tool loading');
  console.log('   3. Use createToolExecutor() for tool execution');
  console.log('\n');

  process.exit(0);
} catch (error) {
  console.error('❌ Error generating AI tools:', error);
  process.exit(1);
}
