# coding: utf-8

"""
    GLAPI - General Ledger and Accounting API

    # GLAPI - Comprehensive Accounting and Revenue Recognition API  GLAPI provides a complete accounting dimensions API with advanced revenue recognition capabilities.  ## Features  - **Multi-tenant Architecture**: Organization-based data isolation - **Accounting Dimensions**: Customers, Vendors, Subsidiaries, Departments, Locations, Classes - **Revenue Recognition**: ASC 606 compliant revenue recognition - **Inventory Management**: Items, Warehouses, Price Lists - **Financial Operations**: Invoices, Payments, Subscriptions - **General Ledger**: Chart of Accounts, GL Transactions  ## Authentication  All endpoints require authentication using Clerk. Include your authentication token in the Authorization header:  ``` Authorization: Bearer YOUR_TOKEN ```  ## Base URL  The API is accessible at: - Development: http://localhost:3031/api - Production: https://api.glapi.io/api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "glapi-sdk"
VERSION = "0.1.0"
PYTHON_REQUIRES = ">= 3.9"
REQUIRES = [
    "urllib3 >= 2.1.0, < 3.0.0",
    "python-dateutil >= 2.8.2",
    "pydantic >= 2",
    "typing-extensions >= 4.7.1",
]

setup(
    name=NAME,
    version=VERSION,
    description="GLAPI - General Ledger and Accounting API",
    author="OpenAPI Generator community",
    author_email="team@openapitools.org",
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "GLAPI - General Ledger and Accounting API"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    long_description_content_type='text/markdown',
    long_description="""\
    # GLAPI - Comprehensive Accounting and Revenue Recognition API  GLAPI provides a complete accounting dimensions API with advanced revenue recognition capabilities.  ## Features  - **Multi-tenant Architecture**: Organization-based data isolation - **Accounting Dimensions**: Customers, Vendors, Subsidiaries, Departments, Locations, Classes - **Revenue Recognition**: ASC 606 compliant revenue recognition - **Inventory Management**: Items, Warehouses, Price Lists - **Financial Operations**: Invoices, Payments, Subscriptions - **General Ledger**: Chart of Accounts, GL Transactions  ## Authentication  All endpoints require authentication using Clerk. Include your authentication token in the Authorization header:  &#x60;&#x60;&#x60; Authorization: Bearer YOUR_TOKEN &#x60;&#x60;&#x60;  ## Base URL  The API is accessible at: - Development: http://localhost:3031/api - Production: https://api.glapi.io/api
    """,  # noqa: E501
    package_data={"glapi": ["py.typed"]},
)